### ISSUE TITLE
An error occurred when uninstalling apatch

### ISSUE THREAD

**Issue by Zenlua** [bmax121/APatch#105]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch
- [X] I will upload bugreport file in APatch Manager - Settings - Report log
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

When I unfortunately uninstalled Apatch, I reinstalled it right after but it came up with unknown error, see screenshot

### To Reproduce

1. Uninstall Apatch
2. Install Apatch.apk
3. Open the application

### Expected behavior

Root permissions remain in applications that have granted root access, but the Apatch manager has shown no longer having root permissions

### Screenshots

![Screenshot_2024-01-11-23-31-24-687_me bmax apatch](https://github.com/bmax121/APatch/assets/143571950/5f3ed7dc-634e-4c56-a062-ec8c4e7d06d9)

### Device info

- Device: raphael k20pro
- OS Version: 14
- APatch Version: 10388
- Kernel Version: 4.14.275

**Comment by marat2509** [comment]
Enter SuperKey, it is reset after reinstalling the application

**Comment by Zenlua** [comment]
Thanks
