### ISSUE TITLE
Xiaomi Redmi K60Pro Boot刷入卡米

### ISSUE THREAD

**Issue by chaojixiaomengxin** [bmax121/APatch#107]
如题

**Comment by chaojixiaomengxin** [comment]
Boot文件https://www.123pan.com/s/tjbzVv-dZaBd.html提取码:Fc97

**Comment by chaojixiaomengxin** [comment]
与另一个问题https://github.com/bmax121/APatch/issues/84 类似或者说一样

**Comment by marat2509** [comment]
Do not use links to third-party forums as a description of the problem. Also, if it is related to a kernel patch not working, not starting device, you need to create an issue in the KernelPatch repository

**Comment by marat2509** [comment]
Do not use links to third-party forums as a description of the problem. Also, if it is related to a kernel patch not working, not starting device, you need to create an issue in the KernelPatch repository

**Comment by marat2509** [comment]
Do not use links to third-party forums as a description of the problem. Also, if it is related to a kernel patch not working, not starting device, you need to create an issue in the KernelPatch repository
