### ISSUE TITLE
Feature Request: Add CLI support

### ISSUE THREAD

**Issue by badabing2005** [bmax121/APatch#119]
To automte the patch creation, it would be nice if Apatch supported CLI commands just like Magisk does.

**Comment by Yervant7** [comment]
Already has

**Comment by marat2509** [comment]
![Screenshot_2024-01-14-14-15-33-353_com.termux-edit.jpg](https://github.com/bmax121/APatch/assets/93652988/c73fe9f9-975b-4d28-94d1-32be83e9715e)

**Comment by badabing2005** [comment]
Thanks,
I wan't too clear, I meant pre-root to be able to create a patch.

But I found it, thanks
I see that you already have similar mechanism to Magisk with [boot_patch.sh](https://github.com/bmax121/APatch/blob/main/app/src/main/assets/boot_patch.sh)

Thanks
