### ISSUE TITLE
Q1.how to use Apatch App Shell cmd Code:  cp   /data/app/apatch.apk to /system/app/apatch.apk  in android 8+;Q2. how to phone power on Auto Run Apatch 

### ISSUE THREAD

**Issue by pigadmin** [bmax121/APatch#130]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch
- [X] I will upload bugreport file in APatch Manager - Settings - Report log
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

such as title

### Device info

- Device:
- OS Version:
- APatch Version:
- Kernel Version:

**Comment by pigadmin** [comment]
Magisk app after  reboot recovery achieve Q.1and Q.2

**Comment by marat2509** [comment]
Describe your problem in more detail, with examples.

**Comment by Zenlua** [comment]
Maybe the su command has a problem, try typing the command: `pm` it will show an error, cmd commands don't work because su has a problem.

**Comment by bmax121** [comment]
/system/app is read only, you can't copy file to it

**Comment by pigadmin** [comment]
> /system/app is read only, you can't copy file to it

# stub.apk           binary    The stub Magisk app to embed into ramdisk.
./magiskboot compress=xz stub.apk stub.xz

provide some methods to  pack apk to xz file  if it's alright.
after android os recovery finish  resume apk file or other files.

![1705671525141](https://github.com/bmax121/APatch/assets/8655006/cef14da3-73ca-4094-a34f-8960781ef0a7)

![1705671525147](https://github.com/bmax121/APatch/assets/8655006/45d3fdcf-af42-4c49-8b05-bde7523edc85)

![1705671525148](https://github.com/bmax121/APatch/assets/8655006/3edc780e-93e3-42e8-838c-bfe528252026)
