### ISSUE TITLE
Apatch cant detected boot has patched 

### ISSUE THREAD

**Issue by Ukiee** [bmax121/APatch#131]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch
- [X] I will upload bugreport file in APatch Manager - Settings - Report log
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Apatch cant detected boot has patched,  so if want update MUST patch clean boot, 
if not it Will Make crash, cant boot & cant boot to recovery,

### Device info

- Device: pixel 3 xl
- OS Version: 13
- APatch Version: manager versi 10419-1-g993c102(8.3)
- Kernel Version: 4.9.337

**Comment by bmax121** [comment]
will be supported later
