### ISSUE TITLE
Apps are adding itself without the user permissions.

### ISSUE THREAD

**Issue by ravindu644** [bmax121/APatch#138]
This weird issue happened after the lastest update, and it's not a problem only with me.

For an example, I didn't add the buy me a coffee app to the superuser section.

![Screenshot_20240115_154115_APatch](https://github.com/bmax121/APatch/assets/126038496/c0653e57-5244-4e2a-a09d-c089d37d832d)

![Screenshot_20240115_154126_Nekogram](https://github.com/bmax121/APatch/assets/126038496/a1c7bbd1-2063-40b0-9b82-7dc0ba32d25e)

**Comment by sinoobie** [comment]
delete app package name that not you want to automatically enable super user permission after reboot on /data/adb/ap/package_config file then reboot your phone.

**Comment by ravindu644** [comment]
> delete app package name that not you want to automatically enable super user permission after reboot on /data/adb/ap/package_config file then reboot your phone.

![Screenshot_20240116_084023_Root Explorer](https://github.com/bmax121/APatch/assets/126038496/b66250cb-7048-49de-aa24-d23238a572cf)
🙁

**Comment by bmax121** [comment]
com.byyoung.setting has root permission, and it's uid is the same with by me a coffee (10381). It's odd. so upload the logs which is guided in issue template

**Comment by symbuzzer** [comment]
Same issue here :(

**Comment by bmax121** [comment]
This issue occurs when you uninstall or install a new app. Try the latest version, closing permissions should prevent it from happening. If it still doesn't work, reopen the issue.
