### ISSUE TITLE
boot 修补文件遗留（boot patch file left behind）

### ISSUE THREAD

**Issue by RejectVanity** [bmax121/APatch#139]
在 data/data/me.bmax.apatch/patch 目录下遗留了若干boot、kernel相关文件，不知道是有用还是没有写删除文件的功能。
（There are several boot and kernel related files left in the "data/data/me.bmax.apatch/patch" directory. I don't know if they are useful or if there is no function to write and delete files.）
![Screenshot_2024-01-15-18-52-28-843_me zhanghai android files-edit](https://github.com/bmax121/APatch/assets/94283631/13a05d30-6a5d-43e7-b055-75270b30ff4a)

**Comment by bmax121** [comment]
It will be deleted next time it is patched. If not, it's a bug
