### ISSUE TITLE
Commands of Magisk module with terminal commands fail to run on terminal emulation

### ISSUE THREAD

**Issue by tinbilly** [bmax121/APatch#141]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch
- [X] I will upload bugreport file in APatch Manager - Settings - Report log
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Magisk module with terminal commands fail to run terminal command

### To Reproduce

1. Flash modules [terminal_systemizer](https://github.com/Magisk-Modules-Repo/terminal_systemizer) and/or [Cache Cleaner](https://github.com/takeru-kageyuki/cache_cleaner)
2. Open Termux - a terminal emulation
3. Enter commands as instructed
- for terminal_systermizer: **_systemize_** OR **_systemize -h_**
- for Cache Cleaner: **_su -c cleaner_**

### Expected behavior

Commands run

### Device info

- Device: moto g8 power
- OS Version: crdroid v7.19
- APatch Version: 10428
- Kernel Version: 4.14.202-perf+

**Comment by Yervant7** [comment]
Disable exclude from termux in APatch

**Comment by tinbilly** [comment]
I tried. But it did not work. I got this error message "/system/bin/sh: cleaner: inaccessible or not found" when running _su -c cleaner_ on Termux.

**Comment by omer-1080314** [comment]
Same for me

![Screenshot_2024-01-30-16-11-05-05_84d3000e3f4017145260f7618db1d683](https://github.com/bmax121/APatch/assets/144014913/320653e0-c149-481a-91ad-f45051e124b5)

![Screenshot_2024-01-30-16-23-59-05_16a6b69c56a7525086be0cba9e63672f](https://github.com/bmax121/APatch/assets/144014913/7bbea28c-22f2-4a57-a72a-a656ad6174d2)

**Comment by bmax121** [comment]
Try the latest version, and if it still doesn't work, reopen the issue.
