### ISSUE TITLE
About the problem of “APatch” manager crashing and unable to run normally when using non-English languages.

### ISSUE THREAD

**Issue by Casun2022** [bmax121/APatch#147]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch
- [X] I will upload bugreport file in APatch Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

After upgrading the “APatch” manager to 10433-2-gbd8cbdf, which is marked as 10435 on Github, there are problems such as verification of super key manager crashing and flashing back and unable to run.
![photo_2024-01-16_22-43-04](https://github.com/bmax121/APatch/assets/130970172/ef1e7739-91bd-49bc-a334-a6b0f1539380)
Supplement: In the subsequent tests, I found that the reason for the manager crash was the language switch problem. The APatch manager is set to follow the system language by default. I adjusted the manager language to English and this problem was properly solved. The manager can be used normally without crashing. This problem seems to only occur when the manager language is not English.

### To Reproduce

1.Download and install the latest version of the manager
2.Open the manager, enter the key to patch the official ROM’s Boot.img and transfer it to the computer
3.Restart the device to FastBoot, connect the device, open the official Google ADB tool “platform-tools”, and use the “fastboot flash boot_ab apatchXXXX.img” command to flash and restart the device
4.Restart the device and enter the system, open the APatch manager to verify the super key

### Expected behavior

Fix the problem that the manager crashes and cannot be used after verifying the super key, and push the version after fixing this problem as soon as possible.

### Screenshots

![Screenshot](https://github.com/bmax121/APatch/assets/130970172/a6621215-8a3e-4b0f-a7ed-8a7f56c68993)

### Logs

[APatch_bugreport_2024-01-16_22_33.tar.gz](https://github.com/bmax121/APatch/files/13951742/APatch_bugreport_2024-01-16_22_33.tar.gz)

### Device info

- Device:XiaoMi 13Pro
- OS Version:HyperOS 1.0.1.0.UMBEUXM
- APatch Version:10433-2-gbd8cbdf
- Kernel Version:5.15.94-android13-8-00001-g171753a15b59-ab11001737

### Additional context

2

**Comment by bmax121** [comment]
fixed
