### ISSUE TITLE
after flash APatch boot. bluetooth no sound.

### ISSUE THREAD

**Issue by zerofo** [bmax121/APatch#154]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch
- [ ] I will upload bugreport file in APatch Manager - Settings - Report log
- [X] My problem is fully stated in English, no reference to outside forums
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

- Bluetooth connect fine. 
- but no sound with the Bluetooth headset.

### To Reproduce

1. flash back the origin boot.img, can fix it.

2. flash the apatch one it can be reproduce

### Device info

- Device: xiaomi 12s ultra.
- OS Version:  Hyperos  24.1.8.DEV
- APatch Version: 10428
- Kernel Version: 5.10.177-android12-9-00001-g219d8dfbba07-ab10551810

### Additional context

File size too big: 25 MB are allowed, 26 MB were attempted to upload.

**Comment by zerofo** [comment]
> That's difficult to figure out why. Does su works?

yes. it work fine.

**Comment by zerofo** [comment]
> That's difficult to figure out why. Does su works?
Additional information:
1. flash the APatch's IMG in bootloader ( if flash it in the TWRP, sometime has some "mount error" about Bluetooth.  )
2. reboot.
then the Bluetooth headset and no sound.

it dont need to install the AndroidPatch. ofc install it, su is work.

**Comment by zerofo** [comment]
It's probably kernel patch's problem.
`If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch`.
but it can boot.

**Comment by zerofo** [comment]
10446 still no sound

**Comment by ravindu644** [comment]
> 10446 still no sound

https://t.me/APatchChannel/42

**Comment by zerofo** [comment]
it fix on 10472.
