### ISSUE TITLE
Loss of root rights

### ISSUE THREAD

**Issue by kodein1** [bmax121/APatch#159]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch
- [X] I will upload bugreport file in APatch Manager - Settings - Report log
- [X] My problem is fully stated in English, no reference to outside forums
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Latest releases of APache lose root after reboot...   
The previous version was without problems

### To Reproduce

I thought some modules were doing it, but except for Z Next and Play integrity fix, I tried all of them

### Device info

- Device: Sony xperia 10IV
- OS Version: stock 14
- APatch Version: 10442
- Kernel Version: 5.4.233 qgki

**Comment by bmax121** [comment]
![image](https://github.com/bmax121/APatch/assets/12316019/40d2d48e-8a55-4dc5-b9df-8d8514225b2a)

**Comment by bmax121** [comment]
fixed
