### ISSUE TITLE
APatch crashes on new version (10450)

### ISSUE THREAD

**Issue by RashadGasimly** [bmax121/APatch#161]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch
- [X] I will upload bugreport file in APatch Manager - Settings - Report log
- [X] My problem is fully stated in English, no reference to outside forums
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

When I open APatch, it crashes

### Screenshots

![Screenshot_20240118_201028_AppErrorsTracking](https://github.com/bmax121/APatch/assets/129990317/d18394f3-1509-471d-ac3b-5009a1c3a3fe)

### Logs

[me.bmax.apatch_2024-01-18T20_11_29.131.log](https://github.com/bmax121/APatch/files/13979034/me.bmax.apatch_2024-01-18T20_11_29.131.log)

### Device info

- Device:Samsung Galaxy A52 4G (SM-A525F/DS)
- OS Version:Android 14
- APatch Version:10450
- Kernel Version:4.14.190

**Comment by ponces** [comment]
Version released was a result of an ongoing work on a PR and should not have been released by the Github action workflow (which should be restricted by changes on the main branch).
Closed.
