### ISSUE TITLE
Riru not detected 

### ISSUE THREAD

**Issue by Datokina** [bmax121/APatch#162]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [ ] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch
- [X] I will upload bugreport file in APatch Manager - Settings - Report log
- [X] My problem is fully stated in English, no reference to outside forums
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Riru supported modules aren't working

### To Reproduce

1. Install riru 
2. Install riru supported module 

### Screenshots

![Screenshot_20240118-201430_APatch](https://github.com/bmax121/APatch/assets/91493715/01e6c73e-ff32-4da9-9c85-16d0183ad92d)

### Logs

[APatch_bugreport_2024-01-18_20_18.tar.gz](https://github.com/bmax121/APatch/files/13979785/APatch_bugreport_2024-01-18_20_18.tar.gz)

### Device info

- Device: SM-G975
- OS Version: 13
- APatch Version: 10450
- Kernel Version: 4.14.316

**Comment by alex193a** [comment]
Riru modules check whether Riru is installed in `/.magisk/modules/riru-core/`, but [KitsuneMagisk's Riru for APatch](https://github.com/KitsuneMagisk/Riru/releases/tag/v26.1.7.r539.c4a63e519a) is actually installed in `/data/adb/modules/riru-core/`. 

You have two options:

1. Unpack the module, fix the riru.sh, and repack it.
2. Use the LSPosed Riru module provided by @Yervant7, which is available [here](https://github.com/Yervant7/LSPosed/releases/tag/v1.9.2-7059).

**Comment by Datokina** [comment]
Thank you
