### ISSUE TITLE
KP模块没有开机自动加载的功能

### ISSUE THREAD

**Issue by sekaiacg** [bmax121/APatch#164]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [ ] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch
- [ ] I will upload bugreport file in APatch Manager - Settings - Report log
- [ ] My problem is fully stated in English, no reference to outside forums
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

目前KP模块只有2种加载方式：
1.apatch app中手动加载
2.通过kpatch 命令操作，这需要参数中带有skey

如果使用AP模块的功能编写一个自动加载脚本会有以下2个问题：
1.不同用户的skey不相同
2.在没有overlayfs支持的设备上无法使用AP模块。
请问有更好的方法吗？

### Device info

- Device:  Xiaomi 12s
- OS Version: 14
- APatch Version:  10446
- Kernel Version: 5.10.94

**Comment by marat2509** [comment]
> * My problem is fully stated in English, no reference to outside forums

**Comment by bmax121** [comment]
1. There's environment vrilable SUPERKEY can be used when loading APM
2. wait for more KPM support
