### ISSUE TITLE
LineageOS修补失败

### ISSUE THREAD

**Issue by c01ns** [bmax121/APatch#165]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch
- [X] I will upload bugreport file in APatch Manager - Settings - Report log
- [X] My problem is fully stated in English, no reference to outside forums
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

LineageOS修补失败

### Device info

- Device:Pixel2XL
- OS Version:Android13
- APatch Version:lastVersion
- Kernel Version:4.4.302
- rom地址：https://download.lineageos.org/devices/taimen/builds
- 日志：
![image](https://github.com/bmax121/APatch/assets/44087084/24b49ca7-8ed6-4c27-bfae-a245a355c1b9)

**Comment by marat2509** [comment]
> * My problem is fully stated in English, no reference to outside forums

**Comment by bmax121** [comment]
wait for support
