### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by pigadmin** [bmax121/APatch#169]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch
- [X] I will upload bugreport file in APatch Manager - Settings - Report log
- [X] My problem is fully stated in English, no reference to outside forums
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

您好。请问有没有方法在修补中把自己写的脚本sh文件一起打入boot镜像。在启动完成时执行呢？

### Device info

- Device:小米8
- OS Version:安卓10
- APatch Version:10420
- Kernel Version:

**Comment by marat2509** [comment]
> * My problem is fully stated in English, no reference to outside forums

**Comment by bmax121** [comment]
Please open an issue for feature support, it may be supported in the future

**Comment by bmax121** [comment]
改成英文，重新提交一个，不然会被关闭

**Comment by pigadmin** [comment]
> 改成英文，重新提交一个，不然会被关闭

有改的， 铁子

**Comment by pigadmin** [comment]
> 改成英文，重新提交一个，不然会被关闭

编号173，就想问问有没有办法像mj一样 写入二进制stub.xz或者sh文件。开机保留apatch app重新修补

**Comment by bmax121** [comment]
#173
