### ISSUE TITLE
scene接收不到apatch的模块

### ISSUE THREAD

**Issue by guozi1373124875** [bmax121/APatch#184]
![Image_1706314609126.jpg](https://github.com/bmax121/APatch/assets/135122698/77c12021-c4fb-409d-b6cc-d0d36a0b9b2f)

![Image_1706314610098.jpg](https://github.com/bmax121/APatch/assets/135122698/8cca2034-43bd-4bed-b484-0d0199d78b2f)

**Comment by chilan666** [comment]
嘟嘟没适配apatch，和apatch有关系吗
