### ISSUE TITLE
[Feature Request] Manager updater or update notifier

### ISSUE THREAD

**Issue by symbuzzer** [bmax121/APatch#194]
Most of the time, we do not notice that there is an update to the Manager application. Old versions of the manager application have been shared in many telegram groups. This may cause serious security problems.For this reason, it would be beneficial to add either an automatic updater or at least an update alert to the manager application.

**Comment by ys1231** [comment]
I see that the update is already supported. Clicking update will download the module compressed package, but it will not install it by itself.
