### ISSUE TITLE
Patch failed, no new-boot.img generated

### ISSUE THREAD

**Issue by Stillhard** [bmax121/APatch#20]
Attached screenshots and files:

![photo_1](https://github.com/bmax121/APatch/assets/219005/352e1fb2-4e28-4bb1-a91a-1dc84250708c)
![photo_2](https://github.com/bmax121/APatch/assets/219005/c2901b93-35b5-4b84-9222-0add29492386)

[APatch_bugreport_2023-12-27_22_32.tar.gz](https://github.com/bmax121/APatch/files/13786390/APatch_bugreport_2023-12-27_22_32.tar.gz)

boot.img file cannot be attached here (size limitation), I've sent it directly to you

**Comment by bmax121** [comment]
open issue at KernelPatch, and upload only kernel which unpacked from boot.img
