### ISSUE TITLE
Motorola G51 5G not boot

### ISSUE THREAD

**Issue by Mxiier** [bmax121/APatch#201]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch
- [X] I will upload bugreport file in APatch Manager - Settings - Report log
- [X] My problem is fully stated in English. 请使用英文，不然会被关闭。
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

![Screenshot_20240205-172859](https://github.com/bmax121/APatch/assets/33021170/a2a3d0c2-2ae0-4224-9bbd-bc38c8a65fa6)
![Screenshot_20240205-172904](https://github.com/bmax121/APatch/assets/33021170/cc47a825-84f6-4fb9-9bbe-3f7c55b8a80c)
![Screenshot_20240205-172923](https://github.com/bmax121/APatch/assets/33021170/0c08f298-6394-443a-a2ca-940395f42fdc)
![Screenshot_20240205-172930](https://github.com/bmax121/APatch/assets/33021170/aeec3e47-033f-4a91-8ae3-f8a0a9e1a629)
![Screenshot_20240205-172938](https://github.com/bmax121/APatch/assets/33021170/40912ade-9c2d-4a54-ad73-80ec50f11467)

### Device info

- Device: moto G51
- OS Version: android 11
- APatch Version:
- Kernel Version: 5.4.86
- KernelPatch Version:

### Additional context

moto g51 not boot
![Screenshot_20240205-172859](https://github.com/bmax121/APatch/assets/33021170/a6d8a064-8f02-45de-b72d-ae861e8e6006)
![Screenshot_20240205-172904](https://github.com/bmax121/APatch/assets/33021170/7ea6015b-89be-4b34-a77b-f9f32270f0fc)
![Screenshot_20240205-172923](https://github.com/bmax121/APatch/assets/33021170/b422e07f-9506-441a-8777-a83aea00d78b)
![Screenshot_20240205-172930](https://github.com/bmax121/APatch/assets/33021170/9e357cbf-9f49-416d-b607-7923f85d1b04)
![Screenshot_20240205-172938](https://github.com/bmax121/APatch/assets/33021170/666d7fd8-5679-4fdb-9e3f-bd0b383a0bbb)

**Comment by bmax121** [comment]
Try the latest version, If it still doesn't work, wait for next update. In fact, if I don't have a phone, I can't solve it either.

**Comment by Hellohi3654** [comment]
I have the same issue on the Motorola Edge 40
I tried the latest stable and latest actions build
