### ISSUE TITLE
grant specific user permissions to a certain software/给予某些app特定用户的权限

### ISSUE THREAD

**Issue by 2032382213** [bmax121/APatch#207]
**APatch KernlePatch & AndroidPatch Version**
KernelPatch:0.8.5 AndroidPatch:10472-2-gb56bd4b
**Are there any issues in the issues that are the same as mine?**
No.
**What is the feature?**
Enable users to grant specific user permissions to a certain software, just like ksu
**What is the use of this feature? For Example:**
I want to grant a app root permission,but it only needs system account permission

**Comment by bmax121** [comment]
This issue occurs when you uninstall or install anew; Try the latest version, closing permissions should prevent it from happening. and if it still doesn't work, reopen the issue.
