### ISSUE TITLE
modules not instaled

### ISSUE THREAD

**Issue by username24646654** [bmax121/APatch#209]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch
- [X] I will upload bugreport file in APatch Manager - Settings - Report log
- [X] My problem is fully stated in English. 请使用英文，不然会被关闭。
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

I haven't tested all the previous versions, but only the APatch_10479-2-g1d4c1ac_10481 version works stably with root access,

//problem
after installing the first module, it is impossible to install the second module, the problem occurs with all modules!

there is a problem with almost all modules:
from /Yervant7/ZygiskNext/releases
to /Dr-TSNG/ZygiskNext/tags

for example, I install lsposed, and after the installation of Zygisk there is a problem

the same thing is on the contrary, if I install Zygisk first (installed / worked), and then install lsposed and shows the error again!

### Screenshots

![photo_2024-02-17_16-52-14](https://github.com/bmax121/APatch/assets/160345180/d2f59878-6f4e-4c1a-bfd9-ae83212a0ea0)

### Device info

- Device: OnePlus 6
- OS Version: Android 11 OxygenOS 11.1.2.2 (original stock)
- APatch Version: APatch_10479-2-g1d4c1ac_10481-release-signed.apk
- Kernel Version: 4.9.227-perf+
- KernelPatch Version:

**Comment by Ashishzzzboop** [comment]
try using diff super key like abcd1234 dont use special char or uppercase letter
