### ISSUE TITLE
[Feature Request] Add a one-click switch to remove the module switch and root permission classification

### ISSUE THREAD

**Issue by Caribeankelp** [bmax121/APatch#211]
如题，另外root权限授权重启丢失的问题烦请开发者辛苦下能否尽快解决

**Comment by marat2509** [comment]
English please.

**Comment by Caribeankelp** [comment]
> English please.

Is it possible to add a one-click switch to remove the module switch and root permission classification?

In addition, the problem of lost root permission authorization to restart is kindly requested by the developers to solve it as soon as possible.

Thanks
