### ISSUE TITLE
Uninstalling androidpatch removes root access to all the apps

### ISSUE THREAD

**Issue by Bertklq1** [bmax121/APatch#215]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch
- [X] I will upload bugreport file in APatch Manager - Settings - Report log
- [X] My problem is fully stated in English. 请使用英文，不然会被关闭。
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

If it is how it is intended to work then it's okay but isn't androidpatch is related to modules.. the. Why uninstalling it removes all the root permission granted to apps and neither can give new root permission to other apps.

### To Reproduce

Uninstall AndroidPatch

_No response_

### Expected behavior

Only modules section should be removed, prior root privileged app should not lose root access and ability to give new root access

_No response_

### Device info

- Device: OnePlus 5
- OS Version:14
- APatch Version:10472
- Kernel Version:4.4.3
- KernelPatch Version:0.8.5

**Comment by bmax121** [comment]
you're right, It will be fixed later

**Comment by bmax121** [comment]
fixed 10570
