### ISSUE TITLE
Executing "reboot" command from Termux will remove all the APModule

### ISSUE THREAD

**Issue by Bertklq1** [bmax121/APatch#217]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch
- [X] I will upload bugreport file in APatch Manager - Settings - Report log
- [X] My problem is fully stated in English. 请使用英文，不然会被关闭。
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Executing "reboot" command from termux reboots the device with all the APModule removed

### To Reproduce

1. Open termux
2. Execute "reboot" command

### Expected behavior

Phone should reboot without uninstalling modules

### Device info

- Device:oneplus 5
- OS Version:14
- APatch Version:10474
- Kernel Version:4.4.302 perf+
- KernelPatch Version:0.8.5

**Comment by bmax121** [comment]
APModule removed after reboot in any way or only when reboot from Termux

**Comment by Bertklq1** [comment]
> APModule removed after reboot in any way or only when reboot from Termux

Only through termux after executing reboot command

**Comment by bmax121** [comment]
Try the latest version, and if it still doesn't work, reopen the issue.

**Comment by ziddey** [comment]
Still an issue on 10933.
