### ISSUE TITLE
Support package name randomization to circumvent simple root detection

### ISSUE THREAD

**Issue by Kruegerrr** [bmax121/APatch#222]
Detecting root by querying the presence of root-related packages has never been a reliable approach. However, if such packages are found on a device, it is a highly suspicious feature and may be targeted by some nasty apps. While it is possible to uninstall APatch after configuring privileges to avoid detection and reinstall it when necessary, this is not an elegant solution. It would be beneficial for APatch to have built-in support for randomizing its package name, similar to Magisk.

**Comment by bmax121** [comment]
yes, we can do this

**Comment by 2825817398** [comment]
[bug--patch-failed.md](https://github.com/bmax121/APatch/files/14548827/bug--patch-failed.md)
