### ISSUE TITLE
fakelocation获取不到root权限

### ISSUE THREAD

**Issue by Sysprcpro** [bmax121/APatch#229]

**Comment by Sysprcpro** [comment]
![Screenshot_2024-03-01-17-11-05-17_72730fc04b0fcba07ef1995658ba2f94.jpg](https://github.com/bmax121/APatch/assets/42271014/db83bba4-6bde-481e-9810-93b66f74b449)

**Comment by Admirepowered** [comment]
ask software author to set the su file as /system/bin/su
![image](https://github.com/bmax121/APatch/assets/43035036/96160083-fd66-4bd6-9073-8d6354dff61a)

**Comment by Sysprcpro** [comment]
what is this app name,please?thank



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月2日(周六) 下午5:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [bmax121/APatch] fakelocation获取不到root权限 (Issue #229)




 
ask software author to set the su file as /system/bin/su
 image.png (view on web)
