### ISSUE TITLE
crux could not power on

### ISSUE THREAD

**Issue by 2936410488** [bmax121/APatch#23]
i use the recovery function on twrp,use boot.emmc.wim patch it,then i flash it into,As a result, the power is not turned on
Is it because my boot doesn't have a ramdisk?

![IMG_20231231_032324_1](https://github.com/bmax121/APatch/assets/132274351/c1a2dc70-e19f-4e48-9d02-8c3059fd994e)
![IMG_20231231_032338_1](https://github.com/bmax121/APatch/assets/132274351/f6231912-7aa1-48e0-8c26-d907625d2dd1)
![IMG_20231231_032353](https://github.com/bmax121/APatch/assets/132274351/0e94d479-187d-4295-b0fa-6919efd75c16)
![IMG_20231231_032355_1](https://github.com/bmax121/APatch/assets/132274351/d311b979-41c0-4eb4-81b6-cdb221be9541)
![IMG_20231231_032958](https://github.com/bmax121/APatch/assets/132274351/681c0fce-852c-4deb-9f1c-0c525cc15e41)

**Comment by bmax121** [comment]
No, I can’t solve the problem of not being able to boot on the device when I don’t have it.
