### ISSUE TITLE
Change of UI

### ISSUE THREAD

**Issue by ssmohanv** [bmax121/APatch#236]
Please consider moving the Clear key button somewhere on the top section of the screen. It is easy to hit the clear key button when trying to hit the modules drawer button. I cleared key few times when trying to acces modules button. 

![Screenshot_20240302-185449](https://github.com/bmax121/APatch/assets/41185231/7c51224c-eac3-4fda-a5fd-e786e4ff5724)

**Comment by pomelohan** [comment]
We had removed the redundant "Clear Key" button from Home page, it's in Settings page now.

The change will be available on next stable release. Please wait patiently.

If you still have issues, feel free to re-open the issue.
