### ISSUE TITLE
AdGuard can't get root permission from apatch

### ISSUE THREAD

**Issue by lingfengyu-dreaming** [bmax121/APatch#257]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch
- [X] I will upload bugreport file in APatch Manager - Settings - Report log
- [X] My problem is fully stated in English.
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

AdGuard have a advanced routing mode that can let AdGuard work with root, and it didn't work with apatch. When I give root for AdGuard in apatch, it can open, but it can't get root permission for its routing mode settings.
When I enable root for AdGuard in apatch, that page can't load, but when I disable root for AdGuard in apatch, it can load the page. I suppose AdGuard might can't get root from apatch. Maybe some problems with `su` or something else in apatch?

### To Reproduce

- 1. give AdGuard root permission in apatch
- 2. open AdGuard and go to its routing mode page
- 3. the page keep loading with root given
- 4. disable root in apatch and try again
- 5. enable(disable) global naming space mode in apatch and try again

### Expected behavior

AdGuard get root successfully and load the page successfully

### Logs

[APatch_bugreport_2024-03-07_21_21.tar.gz](https://github.com/bmax121/APatch/files/14524631/APatch_bugreport_2024-03-07_21_21.tar.gz)

### Device info

- Device: OnePlus ACE2V
- OS Version: ColorOS 14.0.500
- APatch Version: 10474 & 10529
- Kernel Version: 5.10.168-android12-9
- KernelPatch Version: 0.10.2

### Additional context

This issue also report to AdGuard support team, so if not the problem of apatch, can close this issue.
I'm not sure AdGuard team can solve this problem.

**Comment by d-RealMusic-b** [comment]
我也一样，目前只能使用 VPN 模式。😢
Me too, only VPN mode work.😢

**Comment by lingfengyu-dreaming** [comment]
> 没有在模块看到AdGuard，是否是APP应用获取不到root权限

是的。出现问题的是AdGuard For Android。在GitHub上只有用于收集反馈的仓库，故没有贴链接。

**Comment by bmax121** [comment]
Try the newest version

**Comment by lingfengyu-dreaming** [comment]
the latest version fixed
