### ISSUE TITLE
qualcomm crashdump

### ISSUE THREAD

**Issue by ThepuncheXD7** [bmax121/APatch#258]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch
- [X] I will upload bugreport file in APatch Manager - Settings - Report log
- [X] My problem is fully stated in English.
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Hi after i patch my boot image successful a flash it on my phone in fastboot and when reboot i get qualcomm crash dump mode after OnePlus logo 

### To Reproduce

None

### Expected behavior

Boot normal and fully working app

### Screenshots

![Screenshot_20240307-165759](https://github.com/bmax121/APatch/assets/137047884/4364cc04-932f-4141-836a-24c58db30cd8)
![images](https://github.com/bmax121/APatch/assets/137047884/c9070073-1632-4201-bde9-15efa501e1a1)

### Logs

[logs](https://pixeldrain.com/u/43uQQWDF)

### Device info

- Device: OnePlus 7t
- OS Version: android 14
- APatch Version:10529
- Kernel Version:4.14.190-classified
#1 Fri Mar 1 08:26:44 UTC 2024
- KernelPatch Version: 

### Additional context

Link for [Kernel](https://github.com/classified/android_kernel_oneplus_sm8150)

**Comment by bmax121** [comment]
In fact, without a phone, I can't resolve the issue; the only solution is to get a phone or wait for an update.
