### ISSUE TITLE
对于联发科的非GKI2.0内核依旧很难修补成功

### ISSUE THREAD

**Issue by smile349** [bmax121/APatch#26]
这是无法修补的boot镜像下载链接，由于github的上传限制我选择了网盘分享[https://www.123pan.com/s/hYOLVv-e0Keh.html](url)

**Comment by bmax121** [comment]
It cannot be downloaded. You can just upload the kernel and then compress it.

**Comment by smile349** [comment]
[kernel.zip](https://github.com/bmax121/APatch/files/13804646/kernel.zip)
![Screenshot_20231231_014545](https://github.com/bmax121/APatch/assets/122448836/a7b7d4ca-d41e-4d43-91d2-9b9f33c6ec6c)

**Comment by L7RLBsmOOYt7Ypha** [comment]
VIVO MKT810 的 boot, 也无法修补
[Uploading boot.zip…]()

**Comment by ucxl** [comment]
[boot.zip](https://github.com/bmax121/APatch/files/13853685/boot.zip)
也是无法修补

**Comment by bmax121** [comment]
wait KernelPatch update
