### ISSUE TITLE
Failed to grant root to MyAndroidTools

### ISSUE THREAD

**Issue by Fabali** [bmax121/APatch#267]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch
- [X] I will upload bugreport file in APatch Manager - Settings - Report log
- [X] My problem is fully stated in English.
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

MyAnroidTools was granted root with APatch, but it shows no root permission at all.

### Device info

- Device: OnePlus 11
- OS Version: ColorOS 14
- APatch Version: 10533
- Kernel Version: 5.15.94
- KernelPatch Version:0.10.3

**Comment by bugme2** [comment]
juicessh也一样，最新版还是老毛病

**Comment by bugme2** [comment]
juicessh也一样，10533最新版还是老毛病

**Comment by ask9027** [comment]
also there is no root permission while root granted to Mixplorer

**Comment by Typhonling** [comment]
还在用MyAndroidTools的我建议可以尝试一下[https://github.com/lihenggui/blocker](url)

**Comment by Admirepowered** [comment]
Try ci version

**Comment by Admirepowered** [comment]
https://github.com/bmax121/APatch/actions/runs/8617067391

**Comment by pomelohan** [comment]
Fixed on https://github.com/bmax121/APatch/commit/064f079eccfa852f17ca22fdfac8921635ea296d
