### ISSUE TITLE
Can't start patching.

### ISSUE THREAD

**Issue by x1337cn** [bmax121/APatch#27]
![Screenshot_20231231-160525_APatch](https://github.com/bmax121/APatch/assets/54407879/a2cb4247-81ea-4ea3-aeab-003565bc298d)
![Screenshot_20231231-160534_Termux](https://github.com/bmax121/APatch/assets/54407879/d04a8182-acaa-49c6-8b5e-b4dc3091e049)

**Comment by bmax121** [comment]
upload boot.img or kernel image
