### ISSUE TITLE
修复bug

### ISSUE THREAD

**Issue by 2825817398** [bmax121/APatch#278]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch
- [X] I will upload bugreport file in APatch Manager - Settings - Report log
- [X] My problem is fully stated in English.
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

更新之后输入密钥没反应出现bug

### To Reproduce

[APatch_bugreport_2024-03-10_02_12.tar.gz](https://github.com/bmax121/APatch/files/14548871/APatch_bugreport_2024-03-10_02_12.tar.gz)

### Expected behavior

希望修复

### Screenshots

![Screenshot_2024-03-10-12-33-11-146_me bmax apatch](https://github.com/bmax121/APatch/assets/106629063/dc2877b7-7a93-4269-8af9-59a670b0bd90)

### Logs

[bug--patch-failed.md](https://github.com/bmax121/APatch/files/14548865/bug--patch-failed.md)

### Device info

![Screenshot_2024-03-10-12-32-01-885_com android settings](https://github.com/bmax121/APatch/assets/106629063/44c1d3fd-09a1-4f4c-af01-e9efe2cee3e4)

### Additional context

。

**Comment by pomelohan** [comment]
>  My problem is fully stated in English.

Describe in English please and then re-open.
