### ISSUE TITLE
修复bug

### ISSUE THREAD

**Issue by 2825817398** [bmax121/APatch#279]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch
- [X] I will upload bugreport file in APatch Manager - Settings - Report log
- [X] My problem is fully stated in English.
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

After the update, there was no response when entering the key, and worms appeared

### Expected behavior

希望修复

### Screenshots

![Screenshot_2024-03-10-12-33-11-146_me bmax apatch](https://github.com/bmax121/APatch/assets/106629063/e657c0b2-fb73-4532-bf73-0ae16801c037)

### Logs

[APatch_bugreport_2024-03-10_02_12.tar.gz](https://github.com/bmax121/APatch/files/14548894/APatch_bugreport_2024-03-10_02_12.tar.gz)

### Device info

![Screenshot_2024-03-10-12-32-01-885_com android settings](https://github.com/bmax121/APatch/assets/106629063/15b70970-30a6-42ed-a4ea-b32e4d1868d0)

### Additional context

.

**Comment by Admirepowered** [comment]
OTA update will flash boot image,lose su is normal

**Comment by 2825817398** [comment]
> OTA更新会闪存开机映像，丢失su是正常的

请问怎么解决

**Comment by Admirepowered** [comment]
> > OTA更新会闪存开机映像，丢失su是正常的
> 
> 请问怎么解决

等待feature提供刷入另一卡槽的功能或者使用第三方软件在更新前修补镜像

**Comment by Admirepowered** [comment]
ref: #265

**Comment by pomelohan** [comment]
目前暂不支持直接通过 Manager OTA. 请等待后续版本支持，目前你可以再次手动修补后刷入

**Comment by 2825817398** [comment]
> 目前暂不支持直接通过 Manager OTA. 请等待后续版本支持，目前你可以再次手动修补后刷入

已解决感谢，感谢各位的指导！
