### ISSUE TITLE
Apatch not working properly after update 更新Apatch后无法正常使用

### ISSUE THREAD

**Issue by pasical** [bmax121/APatch#305]
### Please check before submitting an issue/在提交 issue 前请检查

- [X] I have searched the issues and haven't found anything relevant/我已经搜索了 issues 列表，没有发现于本问题相关内容
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch/修复失败或刷入修补后镜像不能启动，请前往 KernelPatch 提问
- [X] I will upload bugreport file in APatch Manager - Settings - Report log/我会上传 bureport 文件从 APatch 管理器 - 设置 - 发送日志
- [X] I know how to reproduce the issue which may not be specific to my device/我知道如何重新复现这个问题

### Version requirement/版本要求

- [X] I am using latest CI version of APatch/我正在使用最新 CI 版本

### Describe the bug/描述 bug

更新apatch app后无法使用，同时无法修补镜像。但是已授权的root权限、已安装的模块正常使用。

### Reproduce method/复现方法

将apatch更新至10474以上版本

### Expected behavior/预期行为

-

### Actual behaviour /实际行为

-

### Screenshots/截图

![Screenshot_2024-03-19-10-44-48-228_me bmax apatch](https://github.com/bmax121/APatch/assets/112304778/3b422eef-b59a-4429-9d80-b2dd7262d2a7)
![Screenshot_2024-03-19-10-46-44-563_me bmax apatch](https://github.com/bmax121/APatch/assets/112304778/31e98980-b427-4581-953e-8e483c1e2d0b)
![Screenshot_2024-03-19-10-46-56-728_me bmax apatch](https://github.com/bmax121/APatch/assets/112304778/fa4c5951-3380-4fa5-9112-e6efd4b06cba)

### Device Name/设备名称

xiaomi 13 pro

### OS Version/系统版本

hyperOS/Android14

### APatch Version/APatch 版本

10570

### Kernel Version/内核版本

-

### KernelPatch Version/KernelPatch 版本

-

### Additional context/其他信息

[APatch_bugreport_2024-03-19_10_48.tar.gz](https://github.com/bmax121/APatch/files/14644814/APatch_bugreport_2024-03-19_10_48.tar.gz)

**Comment by bmax121** [comment]
![image](https://github.com/bmax121/APatch/assets/12316019/f8c982cd-9cf4-4748-b942-c7e9a28c6efd)
