### ISSUE TITLE
The password will appear in the IME candidate bar when entering superkey

### ISSUE THREAD

**Issue by RBQcat** [bmax121/APatch#306]
### Please check before submitting an issue/在提交 issue 前请检查

- [X] I have searched the issues and haven't found anything relevant/我已经搜索了 issues 列表，没有发现于本问题相关内容
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch/修复失败或刷入修补后镜像不能启动，请前往 KernelPatch 提问
- [X] I will upload bugreport file in APatch Manager - Settings - Report log/我会上传 bureport 文件从 APatch 管理器 - 设置 - 发送日志
- [X] I know how to reproduce the issue which may not be specific to my device/我知道如何重新复现这个问题

### Version requirement/版本要求

- [X] I am using latest CI version of APatch/我正在使用最新 CI 版本

### Describe the bug/描述 bug

The IME does not consider the text box where superkey is entered to be a password box.  This may lead to accidental leakage of superkey

### Reproduce method/复现方法

1. Click the superkey button 
2. Enter something in the superkey input box 
3. Observe the IME candidate bar

### Expected behavior/预期行为

Passwords should not appear in the IME candidate bar

### Actual behaviour /实际行为

The password appears in the IME candidate bar

### Screenshots/截图

![Screenshot_2024-03-19-13-06-04-472_me bmax apatch](https://github.com/bmax121/APatch/assets/74862110/5308cb52-2f39-4317-8fe3-e06a892d671f)

### Device Name/设备名称

Xiaomi pad 5 pro 5G (enuma)

### OS Version/系统版本

Android 13/MIUI 14.0.4.0

### APatch Version/APatch 版本

APatch_10570-5-ga500f59_10575-release

### Kernel Version/内核版本

N/A

### KernelPatch Version/KernelPatch 版本

N/A

### Additional context/其他信息

Version from CI: https://github.com/bmax121/APatch/actions/runs/8334276634

**Comment by pomelohan** [comment]
Check:
https://github.com/bmax121/APatch/commit/6b13ccfea34cdb3e69246f6a585fa921cd2fb38b

It’s a known bug. When I set the text box to password type, IME was unable to input the password. I suspect it is a bug caused by Compose, and the root cause of this bug has not been figured out yet. I will fix it when I am free.
