### ISSUE TITLE
Module and root manager failed because of bug 错误导致的模块和超级用户管理器失效

### ISSUE THREAD

**Issue by pasical** [bmax121/APatch#322]
### Please check before submitting an issue/在提交 issue 前请检查

- [X] I have searched the issues and haven't found anything relevant/我已经搜索了 issues 列表，没有发现于本问题相关内容
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch/修复失败或刷入修补后镜像不能启动，请前往 KernelPatch 提问
- [X] I will upload bugreport file in APatch Manager - Settings - Report log/我会上传 bureport 文件从 APatch 管理器 - 设置 - 发送日志
- [X] I know how to reproduce the issue which may not be specific to my device/我知道如何重新复现这个问题

### Version requirement/版本要求

- [X] I am using latest CI version of APatch/我正在使用最新 CI 版本

### Describe the bug/描述 bug

系统启动一段时间后模块管理器就会失效，同时root授权页也会失效，在刚启动时可以正常运行，已安装的模块正常运行。

### Reproduce method/复现方法

开机几分钟至几小时内稳定复现

### Expected behavior/预期行为

-

### Actual behaviour /实际行为

如图

### Screenshots/截图

![Screenshot_2024-03-24-21-24-03-741_me bmax apatch](https://github.com/bmax121/APatch/assets/112304778/d00118ff-7218-44c9-b0f9-8709418044bc)
![Screenshot_2024-03-24-21-23-18-923_me bmax apatch](https://github.com/bmax121/APatch/assets/112304778/b6f9c45c-50c0-4cea-946e-7169f716c6a3)

### Device Name/设备名称

xiaomi 13 pro

### OS Version/系统版本

hyperOS/Android14

### APatch Version/APatch 版本

10570

### Kernel Version/内核版本

-

### KernelPatch Version/KernelPatch 版本

-

### Additional context/其他信息

[APatch_bugreport_2024-03-24_21_32.tar.gz](https://github.com/bmax121/APatch/files/14735618/APatch_bugreport_2024-03-24_21_32.tar.gz)

**Comment by pomelohan** [comment]
请提供 bugreport，不然无法修复

**Comment by pasical** [comment]
> 请提供 bugreport，不然无法修复

已上传

**Comment by pomelohan** [comment]
> > 请提供 bugreport，不然无法修复
> 
> 已上传

都装了什么模块

**Comment by pasical** [comment]
> > > 请提供 bugreport，不然无法修复
> > 
> > 
> > 已上传
> 
> 都装了什么模块

![Screenshot_2024-03-24-22-12-14-601_bin mt plus-ed](https://github.com/bmax121/APatch/assets/112304778/77f35fb4-baa3-4569-b43f-2bdff462ec80)
划红线的是没开的

**Comment by pasical** [comment]
是否有可能和网络有关？🤔关闭AdguardHome后暂时未发生问题。

**Comment by pomelohan** [comment]
请尝试最新 ci 版本是否仍然存在问题。

**Comment by pasical** [comment]
目前是10657，刚才看的时候问题依然存在。我再观察几天
[Image]
这是目前的模块列表


________________________________

**Comment by pomelohan** [comment]
QingYue 关了看看

**Comment by pasical** [comment]
目前是开着qingyue，没重启过，三天没问题

**Comment by pasical** [comment]
更新：关闭qingyue后依然复现，猜测是否可能与爱玩机工具箱有关

**Comment by pasical** [comment]
同样复现，近期进行过的操作：更新爱玩机工具箱、更新rex yt模块

**Comment by pasical** [comment]
更新：在10763版本发布至今没有出现问题。
