### ISSUE TITLE
overlayfs is not available unable to install modules

### ISSUE THREAD

**Issue by DiziFire** [bmax121/APatch#33]
hi there i tried to install modules but non of them works for me 
on ap modules page overlay fs is not available module cannot work showing please tell how to fix

**Comment by chilan666** [comment]
This is a problem with your kernel, and APatch can't solve it. The function of AP module depends on overlayfs.

**Comment by ravindu644** [comment]
> hi there i tried to install modules but non of them works for me on ap modules page overlay fs is not available module cannot work showing please tell how to fix

https://t.me/APatchGroup/8355
