### ISSUE TITLE
嵌入内核的 kpm 卸载问题

### ISSUE THREAD

**Issue by 0x0021** [bmax121/APatch#333]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

-

### Describe the solution you'd like/描述你想要的解决方案

内核中已嵌入的内核模块有卸载按钮，可以临时移除，重启后会重新从内核中加载，可否判断内核是否嵌入内核，如果是，增加一个移除模块按钮，实现从内核真正的移除模块
![IMG_20240328_073835](https://github.com/bmax121/APatch/assets/3069412/05831f96-27ec-4dc4-a579-832ce443404a)

### Describe alternatives you've considered/描述您考虑过的备选方案

-

**Comment by bmax121** [comment]
点击嵌入进修补页面可以删掉。不过现在有个笔误导致显示不出来 kpm，下一版改一下就好了

**Comment by pomelohan** [comment]
64f1cd5ff3c3d4f5b7183a776dfc620e4ac977e0
已经修复

临时禁用可以通过新版本的 “控制” 功能（在卸载的按钮旁），根据 KPM 作者的开发可以控制 enable / disable.
