### ISSUE TITLE
Broken root and modules 

### ISSUE THREAD

**Issue by brightkun** [bmax121/APatch#341]
### Please check before submitting an issue/在提交 issue 前请检查

- [X] I have searched the issues and haven't found anything relevant/我已经搜索了 issues 列表，没有发现于本问题相关内容
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch/修复失败或刷入修补后镜像不能启动，请前往 KernelPatch 提问
- [X] I will upload bugreport file in APatch Manager - Settings - Report log/我会上传 bureport 文件从 APatch 管理器 - 设置 - 发送日志
- [X] I know how to reproduce the issue which may not be specific to my device/我知道如何重新复现这个问题

### Version requirement/版本要求

- [X] I am using latest CI version of APatch/我正在使用最新 CI 版本

### Describe the bug/描述 bug

The modules are installed as usual, after a reboot they are displayed, but they do not work

### Reproduce method/复现方法

S

### Expected behavior/预期行为

Usually modules work after a reboot, but they don’t want to work on new versions

### Actual behaviour /实际行为

Non-working modules, even if they are installed

### Screenshots/截图

s

### Logs/日志

S

### Device Name/设备名称

Oppo Realme GT Neo 3T

### OS Version/系统版本

Android 13

### APatch Version/APatch 版本

10570

### Kernel Version/内核版本

4.19.157+

### KernelPatch Version/KernelPatch 版本

0.10.4

### Additional context/其他信息

Please fix this problem, if you need something from me then tell me

**Comment by pomelohan** [comment]
1. No screenshots provided
2. No log provided
3. Description is not enough, I couldn’t understand your meaning. Which module?
4. How do you confirm that it’s not working?

Please provide more details here and re-open it.
