### ISSUE TITLE
System modules not validated

### ISSUE THREAD

**Issue by CMLNT** [bmax121/APatch#344]
### Please check before submitting an issue/在提交 issue 前请检查

- [X] I have searched the issues and haven't found anything relevant/我已经搜索了 issues 列表，没有发现于本问题相关内容
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch/修复失败或刷入修补后镜像不能启动，请前往 KernelPatch 提问
- [X] I will upload bugreport file in APatch Manager - Settings - Report log/我会上传 bureport 文件从 APatch 管理器 - 设置 - 发送日志
- [X] I know how to reproduce the issue which may not be specific to my device/我知道如何重新复现这个问题

### Version requirement/版本要求

- [X] I am using latest CI version of APatch/我正在使用最新 CI 版本

### Describe the bug/描述 bug

<img width="1464" alt="image" src="https://github.com/bmax121/APatch/assets/13372840/4cb7b5a9-ad47-4104-ba9d-fe83958b1b69">
我安装了我自己创建的模块和Zygisk，自动重启后发现模块并未生效
检查/data/adb/modules/ 模块是update状态 
ap/下modules_update.img 存在
断电重启和 adb reboot 重启都不生效
我的机器使用magisk也需要使用特定的magisk mount list方法 

### Reproduce method/复现方法

- 1. app安装模块
- 2. 命令行安装模块都是如此

### Expected behavior/预期行为

模块正常安装

### Actual behaviour /实际行为

模块未能正常安装、且不能卸载

### Device Name/设备名称

B* Auto D*k 5

### OS Version/系统版本

12 api32

### APatch Version/APatch 版本

10630

### Kernel Version/内核版本

5.4.219-qgki

### KernelPatch Version/KernelPatch 版本

0.10.5

### Additional context/其他信息

[2.zip](https://github.com/bmax121/APatch/files/14844939/2.zip)

**Comment by pomelohan** [comment]
“特定的magisk mount list方法” 指的是什么

**Comment by CMLNT** [comment]
> “特定的magisk mount list方法” 指的是什么
请看这个提交
https://github.com/topjohnwu/Magisk/commit/9cfda542298ce6742c5f8278d4700a157543598e

**Comment by pomelohan** [comment]
`Patch @ %08zX [ro.build.system.fission_single_os] -> [ro.build.system.xxxxxxxxxxxxxxxxx]`

我认为这种提交是不必要合并到主线 APatch 的，如果有需要可以自行修改来支持，如果 Magisk / KernelSU 官方版可以正常工作，APatch 不能工作，我们才会修复。

**Comment by CMLNT** [comment]
> `Patch @ %08zX [ro.build.system.fission_single_os] -> [ro.build.system.xxxxxxxxxxxxxxxxx]`
> 
> 我认为这种提交是不必要合并到主线 APatch 的，如果有需要可以自行修改来支持，如果 Magisk / KernelSU 官方版可以正常工作，APatch 不能工作，我们才会修复。

能大概说下我需要修改哪里吗 麻烦了

**Comment by pomelohan** [comment]
请自行研究，我们无法提供帮助。

**Comment by MIkeeJY** [comment]
@CMLNT 我在云机里遇到同样的问题了，有解决方案吗？

**Comment by MIkeeJY** [comment]
> > “特定的magisk mount list方法” 指的是什么
> > 请看这个提交
> > [topjohnwu/Magisk@9cfda54](https://github.com/topjohnwu/Magisk/commit/9cfda542298ce6742c5f8278d4700a157543598e)

我的机器默认magisk 插件是可以的不需要patch

**Comment by pomelohan** [comment]
> > > “特定的magisk mount list方法” 指的是什么
> > > 请看这个提交
> > > [topjohnwu/Magisk@9cfda54](https://github.com/topjohnwu/Magisk/commit/9cfda542298ce6742c5f8278d4700a157543598e)
> 
> 我的机器默认magisk 插件是可以的不需要patch

你的刷入官方 Magisk 可以用吗

**Comment by MIkeeJY** [comment]
@pomelohan 刷入magisk 插件是可用的，Apatch 最新版 插件是灰色 不可点

**Comment by MIkeeJY** [comment]
![image](https://github.com/bmax121/APatch/assets/8580762/c3716374-94b5-49b9-a8f2-5a317a9988b4)
![image](https://github.com/bmax121/APatch/assets/8580762/bd95ff91-9797-4808-a527-526e38f144a8)
[APatch_bugreport_2024-05-20_10_13.tar.gz](https://github.com/bmax121/APatch/files/15371864/APatch_bugreport_2024-05-20_10_13.tar.gz)
最新版截图和log

**Comment by MIkeeJY** [comment]
![image](https://github.com/bmax121/APatch/assets/8580762/fa163ff8-cf76-4892-bb3f-b16a72bccd63)
![image](https://github.com/bmax121/APatch/assets/8580762/2ee832dc-6977-4e74-b8be-89266915c493)
Root功能授权一切正常

**Comment by pomelohan** [comment]
> ![image](https://private-user-images.githubusercontent.com/8580762/331924147-fa163ff8-cf76-4892-bb3f-b16a72bccd63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMTY4MTgsIm5iZiI6MTcxNjIxNjUxOCwicGF0aCI6Ii84NTgwNzYyLzMzMTkyNDE0Ny1mYTE2M2ZmOC1jZjc2LTQ4OTItYmIzZi1iMTZhNzJiY2NkNjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjBUMTQ0ODM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTBjNjNiYWE2NjM1MmZlOTI0YjEyY2FhOWE5MDdlNGNmOGE1ODM2Yjk2ZDg3OGEzNTg3MTFiZjE4NjEyOGZjYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LHJ9xoK5r9MvYQMDDhg-qcu4_qnw4C7mKHmSc2oe-9g) ![image](https://private-user-images.githubusercontent.com/8580762/331924184-2ee832dc-6977-4e74-b8be-89266915c493.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMTY4MTgsIm5iZiI6MTcxNjIxNjUxOCwicGF0aCI6Ii84NTgwNzYyLzMzMTkyNDE4NC0yZWU4MzJkYy02OTc3LTRlNzQtYjhiZS04OTI2NjkxNWM0OTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjBUMTQ0ODM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGY5ODQxMWM2YjQ1ZGRlNGMwNWNlM2FiYTMwOWJhNDEzOTlkNThlNzViMTBlOTFiZTk3ZTJhNTg5Nzc1MmQ2NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.h87rtXe2XL6c4cFndmr8P8xg10difVtUhSkM4rE7OBo) Root功能授权一切正常

我把你那个 issue 重新打开了，后面有空了再研究下什么情况。
