### ISSUE TITLE
Disabling Signature Verification 

### ISSUE THREAD

**Issue by TgStarkTechnology** [bmax121/APatch#345]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

Yes , if Signature verification is enabled then we will unable to load .ko files at kernel level through Apatch & it's necessary to add Disable signature verification with working insmod 

### Describe the solution you'd like/描述你想要的解决方案

.

### Describe alternatives you've considered/描述您考虑过的备选方案

.

### Additional context/其他信息

.

**Comment by TgStarkTechnology** [comment]
.

**Comment by pomelohan** [comment]
Why not write a KPM that disables insmod signature check instead? I don't think it's a work that APatch official should do. You can try it yourself.
