### ISSUE TITLE
Rescuing bricks method

### ISSUE THREAD

**Issue by berlinwow** [bmax121/APatch#351]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

When certain modules installed and can enter the system normally after reboot, but the phone cannot be used normally, like black screen.
In this circumstance, the brick rescue function of Apatch will not be triggered. We need an additional triggering method, such as pressing the volume button.

### Describe the solution you'd like/描述你想要的解决方案

Add functionality to disable the module after pressing the volume button several times

### Describe alternatives you've considered/描述您考虑过的备选方案

No

**Comment by bmax121** [comment]
Have you tried press the volume down several times when system bootimg

**Comment by berlinwow** [comment]
Of course, I also tried using the save brick module and it didn't work properly either.

**Comment by pomelohan** [comment]
@berlinwow Try latest release, we have fixed volume key pressing to enter safe mode
