### ISSUE TITLE
希望增加默认开/关卸载模块的功能

### ISSUE THREAD

**Issue by 149898400** [bmax121/APatch#358]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

类似于KSU的默认开/关卸载模块功能

### Describe the solution you'd like/描述你想要的解决方案

默认开/关卸载模块功能，开启/关闭后可以单独选择单个app进行关闭/开启

### Describe alternatives you've considered/描述您考虑过的备选方案

无

### Additional context/其他信息

无

**Comment by pomelohan** [comment]
Duplicate #253
