### ISSUE TITLE
My phone can only install the first module

### ISSUE THREAD

**Issue by 965973717** [bmax121/APatch#361]
### Please check before submitting an issue/在提交 issue 前请检查

- [X] I have searched the issues and haven't found anything relevant/我已经搜索了 issues 列表，没有发现于本问题相关内容
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch/修复失败或刷入修补后镜像不能启动，请前往 KernelPatch 提问
- [X] I will upload bugreport file in APatch Manager - Settings - Report log/我会上传 bureport 文件从 APatch 管理器 - 设置 - 发送日志
- [X] I know how to reproduce the issue which may not be specific to my device/我知道如何重新复现这个问题

### Version requirement/版本要求

- [X] I am using latest CI version of APatch/我正在使用最新 CI 版本

### Describe the bug/描述 bug

I have successfully installed Apatch,Then I was very happy to install Zygisk-Next.But when installing the second module, an error occurred.
![Screenshot_20240409-030911](https://github.com/bmax121/APatch/assets/79526537/196aed03-07c3-4f2d-81b5-dee879687957)
![Screenshot_20240409-031430](https://github.com/bmax121/APatch/assets/79526537/19563b85-52f6-41d4-8589-7cf15679792e)
trust me, I have tried restarting the phone more than once and turning off the root shell### 

### Reproduce method/复现方法

The first module is installed normally, but the second and any subsequent modules will report an error.

### Expected behavior/预期行为

I can't  understand Why does this happen

### Actual behaviour /实际行为

no thing，I carefully learned how to use this tool, 

### Screenshots/截图

![Screenshot_20240409-030911](https://github.com/bmax121/APatch/assets/79526537/6e04dc0d-b4ea-435f-824d-2bda55c38f59)
![Screenshot_20240409-031430](https://github.com/bmax121/APatch/assets/79526537/d70ceb17-19ea-4db1-b2b9-34f306204049)

### Device Name/设备名称

OnePlus7T

### OS Version/系统版本

OnePlus7THydrogen_11

### APatch Version/APatch 版本

10657

### Kernel Version/内核版本

4.14.190-perf+

### KernelPatch Version/KernelPatch 版本

0.10.5

### Additional context/其他信息

I don't know if this ROM it's old，but I like this ROM,I konw if I install ColorOS All problems are solved ，but I also hope use Hydrogen_11

**Comment by pomelohan** [comment]
>  I will upload bugreport file in APatch Manager - Settings - Report log/我会上传 bureport 文件从 APatch 管理器 - 设置 - 发送日志

无日志无法修复。
