### ISSUE TITLE
Change memory for module.img

### ISSUE THREAD

**Issue by Zenlua** [bmax121/APatch#375]
Add storage like ksu to avoid the problem of not enough throughput if the flash module is heavy.

If you remove module.img so that the directory is the same as magisk, even better 

![Screenshot_2024-04-11-22-56-23-201_bin mt plus-edit](https://github.com/bmax121/APatch/assets/143571950/7fec3b7f-c8de-4a10-a1d2-035b5c49e205)

**Comment by Skorpion96** [comment]
This willl break TWRP backups, people still don't undesrstand this.....

**Comment by xxjoe2** [comment]
agreed, this is why i switched from ksu to ap

**Comment by Skorpion96** [comment]
> agreed, this is why i switched from ksu to ap

@Zenlua is trying (without knowing it I understand) to ruin apatch as well....

**Comment by Skorpion96** [comment]
I really don't know how to pray APatch creator to close this as unfeasible..... Please don't ruin apatch as well.....

**Comment by Zenlua** [comment]
If you don't want to increase the size of the img module file, then delete the img module because it's not suitable. If the module is faulty, leave it like magisk.

**Comment by xxjoe2** [comment]
it really hard to handle that 1T  sparse file, i tried to do a backup under recovery,  but native twrp doesnt work (size exceeded). i backup with tar (sparse file supported) and it took more than hour to complete, just the adb folder!!

so pls dont go back to sparse file

**Comment by 0x0021** [comment]
我拒绝😡

**Comment by Zenlua** [comment]
> it really hard to handle that 1T sparse file, i tried to do a backup under recovery, but native twrp doesnt work (size exceeded). i backup with tar (sparse file supported) and it took more than an hour to complete, just the adb folder!!
> 
> so pls dont go back to sparse file

Just compress module.img into zip and delete module.img it won't take up space.
