### ISSUE TITLE
Original manager crashes (stops working) when hiding manager / 隐藏管理器时，原始管理器崩溃（停止工作）

### ISSUE THREAD

**Issue by cherinyy** [bmax121/APatch#377]
### Please check before submitting an issue/在提交 issue 前请检查

- [X] I have searched the issues and haven't found anything relevant/我已经搜索了 issues 列表，没有发现于本问题相关内容
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch/修复失败或刷入修补后镜像不能启动，请前往 KernelPatch 提问
- [X] I will upload bugreport file in APatch Manager - Settings - Report log/我会上传 bureport 文件从 APatch 管理器 - 设置 - 发送日志
- [ ] I know how to reproduce the issue which may not be specific to my device/我知道如何重新复现这个问题

### Version requirement/版本要求

- [ ] I am using latest CI version of APatch/我正在使用最新 CI 版本

### Describe the bug/描述 bug

The original manager crashes (stops working) when trying to hide it. / 在尝试隐藏管理器时，原始管理器崩溃（停止工作）。

### Reproduce method/复现方法

- 1. Hide Manager / 隐藏管理器

### Expected behavior/预期行为

The manager should be reinstalled with random package names and custom names / 管理器应当以随机包名及自定义名称的形式重新安装

### Actual behaviour /实际行为

Original Manager crashes (stops working) / 原始管理器崩溃（停止工作）

### Device Name/设备名称

OnePlus 3T

### OS Version/系统版本

LineageOS 18.1 / Android 11

### APatch Version/APatch 版本

10657

### Kernel Version/内核版本

3.18.124-perf-gb2a6b3b56106

### KernelPatch Version/KernelPatch 版本

0.10.5

### Additional context/其他信息

Log / 日志: [APatch_bugreport_2024-04-13_16_43.tar.gz](https://github.com/bmax121/APatch/files/14965921/APatch_bugreport_2024-04-13_16_43.tar.gz)

ROM: [18.1-20240305-NIGHTLY-oneplus3](https://download.lineageos.org/devices/oneplus3/builds)

安装最新 CI 构建后无法启动，因此并未使用最新 CI 构建。

**Comment by pomelohan** [comment]
随机管理器包名属于是自欺欺人，仍然有很多方法可以特征，包括但不局限于 libcheck。因此我们已经在最新版本下线这个功能，如果有需求可以考虑 Hide My Applist 等方案，或不用管理器的时候直接将其卸载。
