### ISSUE TITLE
Uninstall/disable Apatch's moudle before moudle apply

### ISSUE THREAD

**Issue by rm52** [bmax121/APatch#382]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

No

### Describe the solution you'd like/描述你想要的解决方案

I installed a moudle which causes bootloop.
Even uninstall Apatch and patch again by Apatch, phone is still bootloop.

### Describe alternatives you've considered/描述您考虑过的备选方案

Is possible uninstall or disable Apatch's moudle after install Apatch apk before boot Aptach's boot.img?
Or a option for uninstall all Apatch's moudle and Apatch itself.
Or disable all moudle at first boot Aptach's boot.img.

**Comment by pomelohan** [comment]
Now you can disable all modules by pressing volume down key 3 times.
