### ISSUE TITLE
Superkey Syntax

### ISSUE THREAD

**Issue by kae0-0** [bmax121/APatch#394]
### Please check before submitting an issue/在提交 issue 前请检查

- [X] I have searched the issues and haven't found anything relevant/我已经搜索了 issues 列表，没有发现于本问题相关内容
- [ ] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch/修复失败或刷入修补后镜像不能启动，请前往 KernelPatch 提问
- [ ] I will upload bugreport file in APatch Manager - Settings - Report log/我会上传 bureport 文件从 APatch 管理器 - 设置 - 发送日志
- [X] I know how to reproduce the issue which may not be specific to my device/我知道如何重新复现这个问题

### Version requirement/版本要求

- [X] I am using latest CI version of APatch/我正在使用最新 CI 版本

### Describe the bug/描述 bug

Usage of some symbols **&** and **( )** may lead to an error or patch freeze in case if they're both used next to each other

### Reproduce method/复现方法

1. Click on the Patch icon
2. Select your boot.img
3. Write any of the mentioned symbols in your Superkey

### Expected behavior/预期行为

Successful patch

### Actual behaviour /实际行为

Error or a freeze

### Screenshots/截图

![Screenshot_20240421-092332_APatch](https://github.com/bmax121/APatch/assets/32288867/bc509008-e308-4a15-9897-818bc2e162ef)

### Device Name/设备名称

Xiaomi 12 (cupid)

### OS Version/系统版本

Evolution X 8.5 (Android 14QPR2)

### APatch Version/APatch 版本

10657

### Kernel Version/内核版本

5.10.205-gki-ga1860f1cbbfb

### KernelPatch Version/KernelPatch 版本

0.10.5

### Additional context/其他信息

not really a solution breaking bug, without these symbols everything works 100%!

**Comment by pomelohan** [comment]
You are not using CI version
