### ISSUE TITLE
Slashes in modules' names are probably not properly escaped when downloading/updating within manager

### ISSUE THREAD

**Issue by lakejason0** [bmax121/APatch#399]
### Please check before submitting an issue/在提交 issue 前请检查

- [X] I have searched the issues and haven't found anything relevant/我已经搜索了 issues 列表，没有发现于本问题相关内容
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch/修复失败或刷入修补后镜像不能启动，请前往 KernelPatch 提问
- [X] I will upload bugreport file in APatch Manager - Settings - Report log/我会上传 bureport 文件从 APatch 管理器 - 设置 - 发送日志
- [X] I know how to reproduce the issue which may not be specific to my device/我知道如何重新复现这个问题

### Version requirement/版本要求

- [X] I am using latest CI version of APatch/我正在使用最新 CI 版本

### Describe the bug/描述 bug

https://github.com/sothx/mipad-magic-window/releases/ 完美横屏应用计划模块的名称前面有“HyperOS For **Pad/Fold**”，其中名称中的斜杠在下载时被错误解读为路径分隔符，导致zip文件错误下载到了新目录当中
![image](https://github.com/bmax121/APatch/assets/36039861/d4c7098a-2d96-46a0-87e6-cf11bf67108f)
并且下载完毕后不会自动安装

### Reproduce method/复现方法

- 1. 安装完美应用横屏计划的旧版本
- 2. 在APatch管理器内选择更新
- 3. 通知中“下载管理”提示下载完成，但APatch不会开始安装，查找下载目录后发现下载的位置如上存在问题

### Expected behavior/预期行为

APatch将zip文件下载到Download文件夹中，而非其子文件夹，并且在下载后能够自动安装

### Actual behaviour /实际行为

下载到了Download/HyperOS For Pad/文件夹下，而且不会开始自动安装

### Device Name/设备名称

Xiaomi Pad 5 Pro 12.4 (dagu), Xiaomi 22081281AC

### OS Version/系统版本

14

### APatch Version/APatch 版本

10657

### Kernel Version/内核版本

4.19.157-perf-gb2d363e0cc8d

### KernelPatch Version/KernelPatch 版本

0.10.5

### Additional context/其他信息

[APatch_bugreport_2024-04-24_10_57.tar.gz](https://github.com/bmax121/APatch/files/15087163/APatch_bugreport_2024-04-24_10_57.tar.gz)

**Comment by pomelohan** [comment]
最新 CI 版本已经修复
