### ISSUE TITLE
[Path Failed] kallsyms kallsyms_num_syms error

### ISSUE THREAD

**Issue by berkedel** [bmax121/APatch#4]
I'm trying to patch a boot.img from Redmi Note 8 Pro, unfortunately got analyze_kallsym_info error. My device partition contains vbmeta and I'm not sure it's related to the issue or not. Fyi, I don't get any issue when patching the boot.img from Mi 10 device. Any pointer how to resolve this issue? Thanks.

**Comment by bmax121** [comment]
Please upload the detailed logs and the boot.img file.
