### ISSUE TITLE
Linux 4.9 内核修补时出现find token_table error

### ISSUE THREAD

**Issue by SakuraKyuo** [bmax121/APatch#405]
### Please check before submitting an issue/在提交 issue 前请检查

- [X] I have searched the issues and haven't found anything relevant/我已经搜索了 issues 列表，没有发现于本问题相关内容
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch/修复失败或刷入修补后镜像不能启动，请前往 KernelPatch 提问
- [X] I will upload bugreport file in APatch Manager - Settings - Report log/我会上传 bureport 文件从 APatch 管理器 - 设置 - 发送日志
- [X] I know how to reproduce the issue which may not be specific to my device/我知道如何重新复现这个问题

### Version requirement/版本要求

- [X] I am using latest CI version of APatch/我正在使用最新 CI 版本

### Describe the bug/描述 bug

在使用Release最新以及CI最新的Apatch在修补Linux 4.9内核时出现find token_table error

### Reproduce method/复现方法

修补下面提供的内核即可复现此问题
内核链接：https://www.123pan.com/s/6pQcjv-QGob.html

### Expected behavior/预期行为

修补成功

### Actual behaviour /实际行为

修补失败 提示find token_table error

### Screenshots/截图
![Screenshot_20240428-104932](https://github.com/bmax121/APatch/assets/63789876/967d1a59-26e7-463d-ad4c-cb6816ac41aa)

### Device Name/设备名称

小米 9 SE

### OS Version/系统版本

Android 14

### APatch Version/APatch 版本

10743（CI构建）

### Kernel Version/内核版本

4.9.337

### KernelPatch Version/KernelPatch 版本

0.10.6

### Additional context/其他信息

[APatch_bugreport_2024-04-28_21_10.tar.gz](https://github.com/bmax121/APatch/files/15142267/APatch_bugreport_2024-04-28_21_10.tar.gz)

**Comment by spew8712** [comment]
請問是如何解決的？
