### ISSUE TITLE
Links in about screen crash if there is no browser installed on system

### ISSUE THREAD

**Issue by gawasvedraj** [bmax121/APatch#407]
### Please check before submitting an issue/在提交 issue 前请检查

- [X] I have searched the issues and haven't found anything relevant/我已经搜索了 issues 列表，没有发现于本问题相关内容
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch/修复失败或刷入修补后镜像不能启动，请前往 KernelPatch 提问
- [X] I will upload bugreport file in APatch Manager - Settings - Report log/我会上传 bureport 文件从 APatch 管理器 - 设置 - 发送日志
- [X] I know how to reproduce the issue which may not be specific to my device/我知道如何重新复现这个问题

### Version requirement/版本要求

- [X] I am using latest CI version of APatch/我正在使用最新 CI 版本

### Describe the bug/描述 bug

APatch tries to open the link in about section but it crashes if there's no browser. (Github and Weblate)

### Reproduce method/复现方法

1. Click 3 dots
2. Open about section
3. Tap on Github or Weblate button

### Expected behavior/预期行为

It shouldn't crash and handle the Exception

### Actual behaviour /实际行为

App crashes because no browser

### Screenshots/截图

![photo_2024-04-28_22-04-12](https://github.com/bmax121/APatch/assets/82878564/64d86df8-5a5d-4f30-b559-79b28620954c)
![photo_2024-04-28_22-04-24](https://github.com/bmax121/APatch/assets/82878564/ba797b83-a4c2-4c37-9164-f018584aff15)

### Logs/日志

https://bin.kv2.dev/~662e74f25de7ed6bfdc25b4b

### Device Name/设备名称

Redmi Note 12 5G

### OS Version/系统版本

Derpfest A14 QPR2

### APatch Version/APatch 版本

10743

### Kernel Version/内核版本

5.4.233-qgki-g9aca48aa2bac

### KernelPatch Version/KernelPatch 版本

0.10.6

### Additional context/其他信息

It might crash on telegram buttons too but since I have telegram installed it opens those links successfully.
Logs:
[APatch_bugreport_2024-04-28_22_07.tar.gz](https://github.com/bmax121/APatch/files/15142826/APatch_bugreport_2024-04-28_22_07.tar.gz)

**Comment by pomelohan** [comment]
In fact most of devices have browser. I have no interested in fixing that. Although I can fix telegram redirect, but `OpenURL for Github` would be still broken.
