### ISSUE TITLE
Overlay hide 

### ISSUE THREAD

**Issue by mdrachen** [bmax121/APatch#425]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

Some device is not support overlay hide during screen record or screen shot

### Describe the solution you'd like/描述你想要的解决方案

This is most demanded thing, overlay hide during screen record or screenshot, please

Asus
Redmagic
MIUI
Samsung
& some other phone

### Describe alternatives you've considered/描述您考虑过的备选方案

.

**Comment by pomelohan** [comment]
...What?

**Comment by CLF233** [comment]
Please provide a video of your operation of `overlay hide`

**Comment by AtopesSayuri** [comment]
Can you provide a video of your operation `overlay hide`

**Comment by pomelohan** [comment]
No response
