### ISSUE TITLE
**Color Theme** interface abnormality

### ISSUE THREAD

**Issue by armv7a** [bmax121/APatch#427]
### Please check before submitting an issue/在提交 issue 前请检查

- [X] I have searched the issues and haven't found anything relevant/我已经搜索了 issues 列表，没有发现于本问题相关内容
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch/修复失败或刷入修补后镜像不能启动，请前往 KernelPatch 提问
- [X] I will upload bugreport file in APatch Manager - Settings - Report log/我会上传 bureport 文件从 APatch 管理器 - 设置 - 发送日志
- [X] I know how to reproduce the issue which may not be specific to my device/我知道如何重新复现这个问题

### Version requirement/版本要求

- [X] I am using latest CI version of APatch/我正在使用最新 CI 版本

### Describe the bug/描述 bug

Clicking on Color Theme interface to switch colors results in abnormal interface.

### Reproduce method/复现方法

1. Click "Settings".
2. Uncheck "System Color Theme".
3. Click "Theme Color".
4. Click on any color.

### Expected behavior/预期行为

It will not cause any abnormal interface.

### Actual behaviour /实际行为

The theme color is switched correctly, but the interface for changing colors appears abnormal.

### Screenshots/截图

https://github.com/bmax121/APatch/assets/147451408/4e3cc1b2-6bf6-477f-8593-921d9281b571

### Device Name/设备名称

Redmi Note 13 Pro+

### OS Version/系统版本

MIUI 14.0.1

### APatch Version/APatch 版本

10763

### Kernel Version/内核版本

5.15.78

### KernelPatch Version/KernelPatch 版本

0.10.7

### Additional context/其他信息

Nothing

**Comment by pomelohan** [comment]
Do you mean it takes a long time before colorThemePicking-dialog disappeared?

**Comment by armv7a** [comment]
> Do you mean it takes a long time before colorThemePicking-dialog disappeared?

yes

**Comment by pomelohan** [comment]
> > Do you mean it takes a long time before colorThemePicking-dialog disappeared?
> 
> yes

But I can't reproduce it on my device and I have no idea about this.

**Comment by pomelohan** [comment]
Send logcat here after reproducing the bug, I thought it was caused by Compose side.

**Comment by pomelohan** [comment]
@armv7a Can you try this build?
https://github.com/bmax121/APatch/actions/runs/9086289036/artifacts/1502811330

**Comment by pomelohan** [comment]
Done in 2d852e7
