### ISSUE TITLE
Hide/fake package name of apatch app

### ISSUE THREAD

**Issue by tomk322** [bmax121/APatch#467]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

On apatch there is no option to change the package name and the id of the app (like on magisk) so the app can be easily detected by other apps.

### Describe the solution you'd like/描述你想要的解决方案

There could be an option to reinstall/update the app with a random package name (similar to magisks "hide magisk app" feature) so that other apps cannot detect this app by its package name.

### Describe alternatives you've considered/描述您考虑过的备选方案

Well I've tried to use lsposed to hide the package name of the app using "hide my applist" module but this does not help because lsposed can't properly hide itself so root is being detected.

**Comment by MIkeeJY** [comment]
You can use lsposed module with Hide-My-Applist https://github.com/Dr-TSNG/Hide-My-Applist to solve this question~

**Comment by veganomy** [comment]
I mean hiding is a simple process right ? Why should we need to install lsposed framework, and then an another app, just to hide this app ?
