### ISSUE TITLE
Root checked！

### ISSUE THREAD

**Issue by MIkeeJY** [bmax121/APatch#468]
### Please check before submitting an issue/在提交 issue 前请检查

- [X] I have searched the issues and haven't found anything relevant/我已经搜索了 issues 列表，没有发现于本问题相关内容
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch/修复失败或刷入修补后镜像不能启动，请前往 KernelPatch 提问
- [X] I will upload bugreport file in APatch Manager - Settings - Report log/我会上传 bureport 文件从 APatch 管理器 - 设置 - 发送日志
- [X] I know how to reproduce the issue which may not be specific to my device/我知道如何重新复现这个问题

### Version requirement/版本要求

- [X] I am using latest CI version of APatch/我正在使用最新 CI 版本

### Describe the bug/描述 bug

Apatch 相关root被检测

### Reproduce method/复现方法

我写了一个demo 关于单独检测apatch的root    https://github.com/MIkeeJY/Root-Checker4Apatch

检测框架来自 https://github.com/scottyab/rootbeer

<img width="270" alt="image" src="https://github.com/bmax121/APatch/assets/8580762/4b60ac85-4c0e-4544-81af-20340cbc52c1">

### Expected behavior/预期行为

Root不应该被检测到

### Actual behaviour /实际行为

Apatch相关Root被检测

### Screenshots/截图

<img width="270" alt="image" src="https://github.com/bmax121/APatch/assets/8580762/032ec736-0d25-4820-9c19-3798ddaf5078">

### Device Name/设备名称

pixel6

### OS Version/系统版本

13

### APatch Version/APatch 版本

APatch_10763_10763-release-signed

### Kernel Version/内核版本

5.10

### KernelPatch Version/KernelPatch 版本

0.10.7

### Additional context/其他信息

请看描述

**Comment by marat2509** [comment]
HyperOS 1.0.3 Xiaomi.eu:

<details><summary>No root detected</summary>

![Screenshot_2024-05-25-02-30-02-238_comg](https://github.com/bmax121/APatch/assets/93652988/bad86c10-a0d5-42a8-867c-5c1f957e7cf8)


![Screenshot_2024-05-25-02-30-41-304_me.bmax.apatch](https://github.com/bmax121/APatch/assets/93652988/f71d07fd-f189-498b-8814-aab1a6b1e6b2)

![Screenshot_2024-05-25-02-30-48-485_me.bmax.apatch](https://github.com/bmax121/APatch/assets/93652988/61052996-1d49-4dae-a2ef-a81a968ccc6b)
</details>

**Comment by MIkeeJY** [comment]
@marat2509 
![image](https://github.com/bmax121/APatch/assets/8580762/ca31fe83-1fe2-4094-88b1-da3cf8fb2c77)
![image](https://github.com/bmax121/APatch/assets/8580762/8dbbcbb6-b0f8-4014-a332-29094b04e864)
![image](https://github.com/bmax121/APatch/assets/8580762/e6f22bd0-e2f8-47fd-adfe-1f619a5153c3)

**Comment by pomelohan** [comment]
> @marat2509 ![image](https://private-user-images.githubusercontent.com/8580762/333767720-ca31fe83-1fe2-4094-88b1-da3cf8fb2c77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NDM2ODAsIm5iZiI6MTcxNjY0MzM4MCwicGF0aCI6Ii84NTgwNzYyLzMzMzc2NzcyMC1jYTMxZmU4My0xZmUyLTQwOTQtODhiMS1kYTNjZjhmYjJjNzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjVUMTMyMzAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjQwODc3YzA3ZTdlMjE3ZTJmN2Q4YmMyODM3NjBhZDUzNzE2M2ZhMDJlYWYzMGIzNWNlYjMzMGY0MTFlNWVmNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.YTTeZUtGSQJ-LBvgWHq-o6wF335bjWo5gBcTUyTecok) ![image](https://private-user-images.githubusercontent.com/8580762/333767730-8dbbcbb6-b0f8-4014-a332-29094b04e864.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NDM2ODAsIm5iZiI6MTcxNjY0MzM4MCwicGF0aCI6Ii84NTgwNzYyLzMzMzc2NzczMC04ZGJiY2JiNi1iMGY4LTQwMTQtYTMzMi0yOTA5NGIwNGU4NjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjVUMTMyMzAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGQ0MmIyMjU2ZDEyNTc2NDk3NjY5NjQwZGMyM2YwYTlkYmZkNWUzM2UzNWFkNmJhZjc5ZTBhMWYxNDQxMTQ1NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.WhuH19dpd24rNR-zqBhe5hcu3ReNfmjNoUWUs6SQseo) ![image](https://private-user-images.githubusercontent.com/8580762/333767750-e6f22bd0-e2f8-47fd-adfe-1f619a5153c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NDM2ODAsIm5iZiI6MTcxNjY0MzM4MCwicGF0aCI6Ii84NTgwNzYyLzMzMzc2Nzc1MC1lNmYyMmJkMC1lMmY4LTQ3ZmQtYWRmZS0xZjYxOWE1MTUzYzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjVUMTMyMzAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2VmZDM4MTUwNzQ0ZDIzZTJjN2Y2MTJhNDkxN2VhZWIwZWM1ZDY3YmIxODdiOWIxM2JmODY0MzVlNjQ0OGUzZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.WyLe1X_t2StBUP8usdp7ssOTv31jenbP_JOaIJlUKpE)

Did you try removing all modules and whether could be detected?

**Comment by MIkeeJY** [comment]
@marat2509 Where can I get lSPosed 1.9.3?

**Comment by marat2509** [comment]
> @marat2509 Where can I get lSPosed 1.9.3? From https://github.com/pumPCin/LSPosed ?

Why not?

**Comment by bmax121** [comment]
@MIkeeJY upload your bug report logs

**Comment by MIkeeJY** [comment]
@bmax121 At last，I know the reason that why it can be checked，
![image](https://github.com/bmax121/APatch/assets/8580762/ed2bb01d-1d4e-408f-8fe4-792be270bc85)
![image](https://github.com/bmax121/APatch/assets/8580762/9b909f01-4540-4afc-9fb8-f21472a31afa)
  public boolean checkForRWPaths() {

        boolean result = false;
       
        //Run the command "mount" to retrieve all mounted directories
        String[] lines = mountReader();

        if (lines == null){
            // Could not read, assume false;
            return false;
        }

        //The SDK version of the software currently running on this hardware device.
        int sdkVersion = android.os.Build.VERSION.SDK_INT;
        
           /**
             *
             *  In devices that are running Android 6 and less, the mount command line has an output as follow:
             *
             *   <fs_spec_path> <fs_file> <fs_spec> <fs_mntopts>
             *
             *   where :
             *   - fs_spec_path: describes the path of the device or remote filesystem to be mounted.
             *   - fs_file: describes the mount point for the filesystem.
             *   - fs_spec describes the block device or remote filesystem to be mounted.
             *   - fs_mntopts: describes the mount options associated with the filesystem. (E.g. "rw,nosuid,nodev" )
             *
             */

            /** In devices running Android which is greater than Marshmallow, the mount command output is as follow:
             *
             *      <fs_spec> <ON> <fs_file> <TYPE> <fs_vfs_type> <(fs_mntopts)>
             *
             * where :
             *   - fs_spec describes the block device or remote filesystem to be mounted.
             *   - fs_file: describes the mount point for the filesystem.
             *   - fs_vfs_type: describes the type of the filesystem.
             *   - fs_mntopts: describes the mount options associated with the filesystem. (E.g. "(rw,seclabel,nosuid,nodev,relatime)" )
             */
        
        for (String line : lines) {

            // Split lines into parts
            String[] args = line.split(" ");

            if ((sdkVersion <= android.os.Build.VERSION_CODES.M && args.length < 4)
                    || (sdkVersion > android.os.Build.VERSION_CODES.M && args.length < 6)) {
                // If we don't have enough options per line, skip this and log an error
                QLog.e("Error formatting mount line: "+line);
                continue;
            }

            String mountPoint;
            String mountOptions;

            /**
             * To check if the device is running Android version higher than Marshmallow or not
             */
            if (sdkVersion > android.os.Build.VERSION_CODES.M) {
                mountPoint = args[2];
                mountOptions = args[5];
            } else {
                mountPoint = args[1];
                mountOptions = args[3];
            }

            for(String pathToCheck: Const.pathsThatShouldNotBeWritable) {
                if (mountPoint.equalsIgnoreCase(pathToCheck)) {

                       /**
                         * If the device is running an Android version above Marshmallow,
                         * need to remove parentheses from options parameter;
                         */
                        if (android.os.Build.VERSION.SDK_INT > android.os.Build.VERSION_CODES.M) {
                            mountOptions = mountOptions.replace("(", "");
                            mountOptions = mountOptions.replace(")", "");

                        }
                    
                    // Split options out and compare against "rw" to avoid false positives
                    for (String option : mountOptions.split(",")){

                        if (option.equalsIgnoreCase("rw")){
                            QLog.v(pathToCheck+" path is mounted with rw permissions! "+line);
                            result = true;
                            break;
                        }
                    }
                }
            }
        }

        return result;
    }     

This method is useful for detecting if critical directories on an Android device are mounted with rw permissions, which can indicate root access. The detection is handled by parsing the mount command output, which varies depending on the Android version, and comparing the mount options against a list of paths that should not be writable.
