### ISSUE TITLE
Add option to patch raw image like magsik

### ISSUE THREAD

**Issue by Joly0** [bmax121/APatch#471]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

Magisk has the option, to install itself, to patch the payload.bin and the raw image that you can simply do a manual install of in most roms.
It would be great to have such an option in apatch aswell. I do not have any custom recovery and therefore cant flash a modified boot.img, also i would need to extract the boot.img first, which is a little hassle aswell. Patching the raw image file directly would make it probably a lot easier for people t ibstall apatch.

### Describe the solution you'd like/描述你想要的解决方案

Option in apatch to patch raw image file and maybe payload.bin (raw image highly preferred)

### Describe alternatives you've considered/描述您考虑过的备选方案

None

**Comment by bmax121** [comment]
maybe you need a kptools ? (KernelPatch release)

**Comment by Joly0** [comment]
> maybe you need a kptools ? (KernelPatch release)

I am not sure what you mean?

**Comment by bmax121** [comment]
https://github.com/bmax121/KernelPatch/releases/download/0.10.7/kptools-linux

**Comment by Joly0** [comment]
Still not sure how this is supposed to help me or answer my feature request?

**Comment by bmax121** [comment]
sorry, I thought it was the kernel image. as for payload.bin, we don't have time to support it
