### ISSUE TITLE
重写sepolicy rules

### ISSUE THREAD

**Issue by smile349** [bmax121/APatch#478]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

magisk sepolicy很容易被检测

### Describe the solution you'd like/描述你想要的解决方案

magisk是安卓上近几年来最广泛的root方案，检测手段早已泛滥，apatch现在已经不是初期阶段了，完全不应该继续使用magisk sepolicy

### Describe alternatives you've considered/描述您考虑过的备选方案

基于magisk sepolicy进行修改

**Comment by bmax121** [comment]
欢迎 pr ，或者KPM绕过，
另外你所的是哪些检测手段
