### ISSUE TITLE
Use root permisson to "Patch and flash" / 使用root权限进行“修补并安装”

### ISSUE THREAD

**Issue by MarisaDAZA** [bmax121/APatch#491]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

No/不是

### Describe the solution you'd like/描述你想要的解决方案

Can we use root permisson to "Patch and flash", just like Magisk?  By doing this, it will be easier to switch to apatch from other root manager. For now, this feature is only available after flashed apatch kernel.
能否像Magisk一样获取root权限进行“修补并安装”，这样从其他root管理器切换到apatch会更方便。现在这个功能仅在刷入了apatch内核后可用。

### Describe alternatives you've considered/描述您考虑过的备选方案

Use fastboot to flash it.
用fastboot刷入。

**Comment by pomelohan** [comment]
没有技术难点，单纯故意不做，因为 APatch 这个项目不像 KernelSU / Magisk 等风险较低，即使是可以修补成功，也有可能无法开机，因此这样做可以最大化保证用户在刷入前有自救的方式。

**Comment by MarisaDAZA** [comment]
最新版本有直接安装的选项了，但是安装以后Magisk和APatch的补丁似乎会同时存在
