### ISSUE TITLE
包含$等字符,输入 SuperKey 会提示鉴权失败

### ISSUE THREAD

**Issue by abctensor** [bmax121/APatch#501]
### Please check before submitting an issue/在提交 issue 前请检查

- [X] I have searched the issues and haven't found anything relevant/我已经搜索了 issues 列表，没有发现于本问题相关内容
- [ ] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch/修复失败或刷入修补后镜像不能启动，请前往 KernelPatch 提问
- [ ] I will upload bugreport file in APatch Manager - Settings - Report log/我会上传 bureport 文件从 APatch 管理器 - 设置 - 发送日志
- [X] I know how to reproduce the issue which may not be specific to my device/我知道如何重新复现这个问题

### Version requirement/版本要求

- [X] I am using latest CI version of APatch/我正在使用最新 CI 版本

### Describe the bug/描述 bug

patch boot.img时设置 SuperKey 包含$等字符，刷写后输入SuperKey会提示鉴权失败。

### Reproduce method/复现方法

1.use apatch patch boot.img
2.SuperKey like : "XXXXX$XXX"
3.adb pull patched.boot.img
4.fastboot flash boot patched.boot.img
5.fastboot reboot 
6.input SuperKey
7.鉴权失败

### Expected behavior/预期行为

我希望能在修补时限定superkey格式，或者转换合法的中间密钥存储。

### Actual behaviour /实际行为

没有限定superkey格式鉴权失败

### Device Name/设备名称

OPPO PKM80

### OS Version/系统版本

Android11

### APatch Version/APatch 版本

latest CI  10763

### Kernel Version/内核版本

4.19.237+

### KernelPatch Version/KernelPatch 版本

0.10.7

### Additional context/其他信息

输入SuperKey会提示鉴权失败

**Comment by pomelohan** [comment]
试试 CI 版
