### ISSUE TITLE
su进程泄露

### ISSUE THREAD

**Issue by smile349** [bmax121/APatch#509]
### Please check before submitting an issue/在提交 issue 前请检查

- [X] I have searched the issues and haven't found anything relevant/我已经搜索了 issues 列表，没有发现于本问题相关内容
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch/修复失败或刷入修补后镜像不能启动，请前往 KernelPatch 提问
- [X] I will upload bugreport file in APatch Manager - Settings - Report log/我会上传 bureport 文件从 APatch 管理器 - 设置 - 发送日志
- [X] I know how to reproduce the issue which may not be specific to my device/我知道如何重新复现这个问题

### Version requirement/版本要求

- [X] I am using latest CI version of APatch/我正在使用最新 CI 版本

### Describe the bug/描述 bug

只要在终端中执行了su命令，其他APP就能发现su进程（其他应用无root权限）

### Reproduce method/复现方法

打开momo，没有找到su进程，去终端中执行su命令后momo找到su进程

### Expected behavior/预期行为

momo只要未被授予root权限，都找不到su进程

### Actual behaviour /实际行为

终端中执行su命令后momo找到su进程

### Screenshots/截图

![Screenshot_2024-06-12-23-25-44-007_io github vvb2060 mahoshojo](https://github.com/bmax121/APatch/assets/122448836/7a4089c0-043a-44fc-86a4-d3caa850fcbd)

### Logs/日志

不需要日志，在最新ci版apatch上稳定复现

### Device Name/设备名称

红米note10pro（chopin）

### OS Version/系统版本

安卓13

### APatch Version/APatch 版本

10815

### Kernel Version/内核版本

4.14.186

### KernelPatch Version/KernelPatch 版本

0.10.7

### Additional context/其他信息

无

**Comment by pomelohan** [comment]
最新 CI 已修复
