### ISSUE TITLE
最新测试版无法修补

### ISSUE THREAD

**Issue by lxx12445** [bmax121/APatch#510]
### Please check before submitting an issue/在提交 issue 前请检查

- [X] I have searched the issues and haven't found anything relevant/我已经搜索了 issues 列表，没有发现于本问题相关内容
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch/修复失败或刷入修补后镜像不能启动，请前往 KernelPatch 提问
- [X] I will upload bugreport file in APatch Manager - Settings - Report log/我会上传 bureport 文件从 APatch 管理器 - 设置 - 发送日志
- [X] I know how to reproduce the issue which may not be specific to my device/我知道如何重新复现这个问题

### Version requirement/版本要求

- [X] I am using latest CI version of APatch/我正在使用最新 CI 版本

### Describe the bug/描述 bug

最新测试10763-65-g178e3db_10828-release-signed无法直接刷入，通过修补boot刷入成功但是无法授权也无法刷入zygisk next和lsposed，显示版本报错22

### Reproduce method/复现方法

更新
修补刷入

### Expected behavior/预期行为

正常修补刷入

### Actual behaviour /实际行为

没法正常修补

### Screenshots/截图

![Screenshot_2024-06-12-23-32-07-067_me bmax apatch](https://github.com/bmax121/APatch/assets/133146656/8e263bd2-d527-4b6e-8b81-2fa4c3ab3205)

### Device Name/设备名称

k40s （munch）

### OS Version/系统版本

android12 miui13

### APatch Version/APatch 版本

APatch_10763-65-g178e3db_10828-release-signed

### Kernel Version/内核版本

4.19

### KernelPatch Version/KernelPatch 版本

0.10.7

### Additional context/其他信息

[Uploading APatch_bugreport_2024-06-12_23_43.tar.gz.zip…]()

**Comment by miuirussia** [comment]
Confirm it with different message

![Screenshot_2024-06-12-14-11-41-196_me bmax apatch](https://github.com/bmax121/APatch/assets/1270028/efd4db0e-d7fe-4cf4-abad-848d76cbdbd7)

**Comment by lxx12445** [comment]
使用刷入boot.img安装成功，但是默认su路径变为/system/bin/kp,需要修改为/system/bin/su才能获取root，重启后失效，su路径变回kp
![Screenshot_2024-06-13-10-17-35-523_me bmax apatch](https://github.com/bmax121/APatch/assets/133146656/fc92a530-a5d5-40b4-8620-411f07865459)

**Comment by lxx12445** [comment]
![Screenshot_2024-06-13-10-16-49-100_me bmax apatch](https://github.com/bmax121/APatch/assets/133146656/301f4c70-f2f7-4f85-ac77-cbe27673cc2c)
模块无法刷入，shell权限已取消
![Screenshot_2024-06-13-10-17-28-094_me bmax apatch](https://github.com/bmax121/APatch/assets/133146656/3c71a106-19b4-4620-a2da-d434945bcd15)

**Comment by lxx12445** [comment]
日志
[APatch_bugreport_2024-06-13_10_26.tar.gz.zip](https://github.com/user-attachments/files/15812936/APatch_bugreport_2024-06-13_10_26.tar.gz.zip)

**Comment by pomelohan** [comment]
应该修了，可以再试试。Zygisk Next 不能用是已知问题
