### ISSUE TITLE
APModule install icon/button dissapears randomly.

### ISSUE THREAD

**Issue by gyrorayo** [bmax121/APatch#525]
### Please check before submitting an issue/在提交 issue 前请检查

- [X] I have searched the issues and haven't found anything relevant/我已经搜索了 issues 列表，没有发现于本问题相关内容
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch/修复失败或刷入修补后镜像不能启动，请前往 KernelPatch 提问
- [X] I will upload bugreport file in APatch Manager - Settings - Report log/我会上传 bureport 文件从 APatch 管理器 - 设置 - 发送日志
- [X] I know how to reproduce the issue which may not be specific to my device/我知道如何重新复现这个问题

### Version requirement/版本要求

- [X] I am using latest CI version of APatch/我正在使用最新 CI 版本

### Describe the bug/描述 bug

Hi, noticed this a while ago, I wanted to install a module, but couldn't find the install button, weird thing, as I could install several modules before. Restarted the device, checked again, NO Install button. Hours later, had to reboot my device (unrelated to module installing activity), wanted to check again aaaand the button WAS FINALLY BEING DISPLAYED.

1. **Bug is NOT NECESSARILY triggered by reboots**, it can dissapear at any time.
2. **KPModule install icon/button is not affected by this bug**. 

### Reproduce method/复现方法

1. Reboot device (or not)
2. Launch APManager
3. Go to APModule tab
4. **There is no install icon/button**

### Expected behavior/预期行为

On APModule tab, there should be an install icon/button on the bottom-right corner of the screen. 

### Actual behaviour /实际行为

No install icon/button in APModule tab, KPModule tab is **not affected**.

### Screenshots/截图

![WhatsApp Image 2024-06-24 at 12 14 19 PM](https://github.com/bmax121/APatch/assets/63332428/85676c71-1dc3-4d10-8c27-a74dbf8b091d)
![WhatsApp Image 2024-06-24 at 12 11 47 PM](https://github.com/bmax121/APatch/assets/63332428/60d1e17e-51cb-40bd-916b-3a2e83d96b73)

### Logs/日志

[APatch_bugreport_2024-06-24_12_13.tar.gz](https://github.com/user-attachments/files/15959834/APatch_bugreport_2024-06-24_12_13.tar.gz)

### Device Name/设备名称

Xiaomi Redmi 23129RA5FL (Redmi Note 13 4G)

### OS Version/系统版本

HyperOS 1.0.3 by xiaomi.eu (Android 14)

### APatch Version/APatch 版本

**10844 and 10849**

### Kernel Version/内核版本

6.15.123-android13-8-00044

### KernelPatch Version/KernelPatch 版本

0.11.0

### Additional context/其他信息

Thought that the issue was caused by switching launchers (Nova Launcher/HyperOS Launcher), I'm not really sure now,  as I tried to reproduce the steps a few hours ago to update this post and I couldn't manage to reproduce the bug again.

EDIT: Uninstalled third party launcher, didn't reboot the device and yet, the icon keeps dissapearing randomly.

**Comment by gyrorayo** [comment]
Sorry, fixed it by updating: **10844 > 10849**

**Comment by pomelohan** [comment]
Yes, this is a known issue but we are busy, not fixed yet. Thanks for reporting.

**Comment by gyrorayo** [comment]
fixed in 10857
