### ISSUE TITLE
cannot input superkey after update

### ISSUE THREAD

**Issue by Jason20110517** [bmax121/APatch#546]
### Please check before submitting an issue/在提交 issue 前请检查

- [X] I have searched the issues and haven't found anything relevant/我已经搜索了 issues 列表，没有发现于本问题相关内容
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch/修复失败或刷入修补后镜像不能启动，请前往 KernelPatch 提问
- [X] I will upload bugreport file in APatch Manager - Settings - Report log/我会上传 bureport 文件从 APatch 管理器 - 设置 - 发送日志
- [X] I know how to reproduce the issue which may not be specific to my device/我知道如何重新复现这个问题

### Version requirement/版本要求

- [X] I am using latest CI version of APatch/我正在使用最新 CI 版本

### Describe the bug/描述 bug

从旧版A patch升级到最近，顶部提示“未安装或鉴权”，我在旧版本安装过Apatch，于是我点击超级密钥，但是输入后我不能点击确定，灰色的按钮不能点击，我肯定我安装过且密码就是1145

### Reproduce method/复现方法

见描上边描述

### Expected behavior/预期行为

输入密钥，验证成功

### Actual behaviour /实际行为

不让输入

### Screenshots/截图

![Screenshot_20240716-071309_APatch](https://github.com/user-attachments/assets/1aabe408-f7ce-465a-bf31-da9f4df02027)

### Device Name/设备名称

小米平板6pro

### OS Version/系统版本

paranoid android 

### APatch Version/APatch 版本

10763

### Kernel Version/内核版本

5.0.177

### KernelPatch Version/KernelPatch 版本

I don't know 

### Additional context/其他信息

nothing

**Comment by pomelohan** [comment]
新版强制要求密码大于等于8位且不允许纯数字或字符，请重新修补
