### ISSUE TITLE
[Manager Improvement] Add support for Devices with arm64 kernel but the system is in arm32 mode.

### ISSUE THREAD

**Issue by ravindu644** [bmax121/APatch#55]
Both Apatch and KSU apps can't be installed on a arm32 system, it says "application not installed".

But most of the time, these devices are using an arm64 kernel. is it possible to make the app work in arm32 devices too?

I can even patch the boot from apatch for my arm32 Galaxy A01.

**Comment by Yervant7** [comment]
Check your CPU machine if it is armv8l need to create new support in KernelPatch too

**Comment by ravindu644** [comment]
> Check your CPU machine if it is armv8l need to create new support in KernelPatch too

Scamsung fu*ked this phone.

![20240114_135804](https://github.com/bmax121/APatch/assets/126038496/9a9d1440-a830-4dfd-a8e4-e77550f5b395)

**Comment by bmax121** [comment]
hi, bro.  That's not easy, all the libraries need to be compatible, and kpimg need to do some compat too

**Comment by ravindu644** [comment]
> hi, bro. That's not easy, all the libraries need to be compatible, and kpimg need to do some compat too

It's ok. Understood😌😊
