### ISSUE TITLE
Help!!! APatch 10763 with Kernel 4.4.146 

### ISSUE THREAD

**Issue by DerBaliner** [bmax121/APatch#551]
Hi,

I need help!!!

I have successfully installed APatch 10763 on my UMIDIGI A5 Pro with kernel 4.4.146 and patched the boot image and successfully set the super key.

After I flashed the patched boot image with TWRP in the boot partition and restart the device, it reboots when the boot splash of the start screen appears.

I have successfully booted into the safe boot loop mode and get to the start screen, after a short time the device restarts.

Could it be that it has something to do with the kernel configuration? 

https://github.com/bmax121/APatch?tab=readme-ov-file#requirement

[APatch_bugreport_2024-07-17_17_41.tar.gz](https://github.com/user-attachments/files/16268338/APatch_bugreport_2024-07-17_17_41.tar.gz)

![Screenshot_20240717-173247_APatch](https://github.com/user-attachments/assets/534047ff-fdc2-401f-9022-11012d95592a)
![Screenshot_20240717-172338_Ortus Launcher](https://github.com/user-attachments/assets/9d8c68d6-a2d3-4434-85ee-27230deea2bd)
![Screenshot_20240717-165359_APatch](https://github.com/user-attachments/assets/51e7ba7d-de2e-4968-89fd-4adcf0df90db)
![Screenshot_20240716-195416_Settings](https://github.com/user-attachments/assets/642a61e5-2f1b-4796-a363-4ad04b42ffb6)
![Screenshot_20240716-195252_APatch](https://github.com/user-attachments/assets/ba0454c0-0497-48d3-88f4-16962cc3586a)

_Originally posted by @DerBaliner in https://github.com/bmax121/APatch/discussions/547_

**Comment by DerBaliner** [comment]
I have now tried with version 0.10.7 and 0.11.0-dev, both boot without bootloop, but when I enter the super key, authentication fails again 🤔
https://kernelpatch-demo.pages.dev/

**Comment by gyrorayo** [comment]
Device/kernel not compatible?
Have you tried with your stock rom?

**Comment by DerBaliner** [comment]
> Device/kernel not compatible? Have you tried with your stock rom?

CONFIG_KALLSYMS_ALL=n
I have use from stock

A nice guy from XDA say to me, find kernel sources for mt6763
https://xdaforums.com/t/2024-full-guide-a14-qpr-3-apatch-ksu-microg-install-gsis-on-nabu-by-exam-with-leos-u-base-on-ponses-aosp-risingos-gsi.4675386/page-3

**Comment by gyrorayo** [comment]
Yes, I've read  the thread, he gave you the steps to configure and compile your kernel, not a problem with APatch

**Comment by DerBaliner** [comment]
> Yes, I've read the thread, he gave you specific steps to configure and compile your kernel, this issue is not a problem with APatch

Yep, I know
I close the issue and thx 😉
