### ISSUE TITLE
最新CI 开启root后需要重启才生效

### ISSUE THREAD

**Issue by CCCC-L** [bmax121/APatch#555]
### Please check before submitting an issue/在提交 issue 前请检查

- [X] I have searched the issues and haven't found anything relevant/我已经搜索了 issues 列表，没有发现于本问题相关内容
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch/修复失败或刷入修补后镜像不能启动，请前往 KernelPatch 提问
- [X] I will upload bugreport file in APatch Manager - Settings - Report log/我会上传 bureport 文件从 APatch 管理器 - 设置 - 发送日志
- [X] I know how to reproduce the issue which may not be specific to my device/我知道如何重新复现这个问题

### Version requirement/版本要求

- [X] I am using latest CI version of APatch/我正在使用最新 CI 版本

### Describe the bug/描述 bug

最新CI 开启root后需要重启才生效

### Reproduce method/复现方法

超级用户页面，点击右边的按钮

### Expected behavior/预期行为

直接生效不需要重启

### Actual behaviour /实际行为

需要重启

### Screenshots/截图

![Screenshot_20240720_001512](https://github.com/user-attachments/assets/2eb90189-c60a-4db6-9d99-d9bbbfb95530)
![Screenshot_20240720_001525_KonaBess](https://github.com/user-attachments/assets/aee5aca8-9e6a-4f1b-b22d-04e213c93f73)

### Device Name/设备名称

三星 TabS7

### OS Version/系统版本

OneUI5.1

### APatch Version/APatch 版本

10873

### Kernel Version/内核版本

4.19.113

### KernelPatch Version/KernelPatch 版本

0.10.7

### Additional context/其他信息

[APatch_bugreport_2024-07-20_00_11.tar.gz](https://github.com/user-attachments/files/16314545/APatch_bugreport_2024-07-20_00_11.tar.gz)

**Comment by pomelohan** [comment]
请升级 KP 到 0.11.0-dev 版本，不匹配导致。
