### ISSUE TITLE
supports the 32 bit

### ISSUE THREAD

**Issue by Georgeramzy** [bmax121/APatch#565]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

I want to support the 32-bit system, so I want to use Apatch Root because it is the best in terms of hiding

### Describe the solution you'd like/描述你想要的解决方案

Supports 32-bit operating system. If Apatch root does not work, please state the reason.

### Describe alternatives you've considered/描述您考虑过的备选方案

There are no alternatives.

### Additional context/其他信息

I really hope you make Apache root available for 32 bit system as I mentioned before it is very good at hiding root

**Comment by Aruvelut-123** [comment]
+1 for WSA
