### ISSUE TITLE
Some modules arent recognizing after 10882

### ISSUE THREAD

**Issue by jooomoooj** [bmax121/APatch#571]
### Please check before submitting an issue/在提交 issue 前请检查

- [X] I have searched the issues and haven't found anything relevant/我已经搜索了 issues 列表，没有发现于本问题相关内容
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch/修复失败或刷入修补后镜像不能启动，请前往 KernelPatch 提问
- [X] I will upload bugreport file in APatch Manager - Settings - Report log/我会上传 bureport 文件从 APatch 管理器 - 设置 - 发送日志
- [X] I know how to reproduce the issue which may not be specific to my device/我知道如何重新复现这个问题

### Version requirement/版本要求

- [X] I am using latest CI version of APatch/我正在使用最新 CI 版本

### Describe the bug/描述 bug

Yt revanced isnt recognized, tried clean module installation still not working. 

### Reproduce method/复现方法

Flash yt revanced module
Reboot
Check module status and app itself

### Expected behavior/预期行为

Should work.

### Actual behaviour /实际行为

Doesnt work it says needs to reflash, used to work in previous version.

### Screenshots/截图

![Screenshot_20240729-171445_APatch](https://github.com/user-attachments/assets/ac8aad35-23bd-48db-b5dd-b85c597f9981)
![Screenshot_20240729-171450_APatch](https://github.com/user-attachments/assets/0ad53b3e-3e0b-4a4a-9416-82e353742d83)
![Screenshot_20240729-172436_Settings](https://github.com/user-attachments/assets/9d691636-21f0-41d0-947a-0eb043d15911)

### Logs/日志

[trigger_post-mount.log](https://github.com/user-attachments/files/16410555/trigger_post-mount.log)
[trigger_boot-completed.log](https://github.com/user-attachments/files/16410556/trigger_boot-completed.log)
[trigger_service.log](https://github.com/user-attachments/files/16410557/trigger_service.log)

### Device Name/设备名称

Xiaomi Mi A1 (tissot)

### OS Version/系统版本

14

### APatch Version/APatch 版本

10882

### Kernel Version/内核版本

4.9.337

### KernelPatch Version/KernelPatch 版本

0.11.1

### Additional context/其他信息

.

**Comment by chase535** [comment]
This is because SELinux, I don't know this is a bug or a new feature.
A simple solution is add ```setenforce 0``` at the beginning of service.sh, and add ```setenforce 1``` at the end of service.sh. And I found
A more complicated solution is use ```/data/system/packages.xml``` file instead of ```dumpsys``` command, so you can get application info without change SELinux status. Modified service.sh file just like this:
```
#!/system/bin/sh
MODDIR=${0%/*}
[ -z "${NVBASE}" ] && NVBASE=/data/adb
RVPATH=$NVBASE/rvhc/${MODDIR##*/}.apk
. "$MODDIR/config"

err() {
	[ ! -f "$MODDIR/err" ] && cp "$MODDIR/module.prop" "$MODDIR/err"
	sed -i "s/^des.*/description=⚠️ Needs reflash: '${1}'/g" "$MODDIR/module.prop"
}

until [ "$(getprop sys.boot_completed)" = 1 ]; do sleep 1; done
until [ -d "/sdcard/Android" ]; do sleep 1; done

rm -f ${MODDIR}/packages.xml
if [ ! -f "/data/system/packages.xml" ]; then
  err "packages.xml not found"
	exit
elif [ -z "$(file /data/system/packages.xml | grep 'Binary')" ]; then
  cp -f /data/system/packages.xml ${MODDIR}/packages.xml
elif ! which abx2xml > /dev/null; then
  err "abx2xml tool not found"
	exit
else
  abx2xml /data/system/packages.xml ${MODDIR}/packages.xml
fi

PACKAGE_INFO=$(grep "<package name=\"${PKG_NAME}\"" ${MODDIR}/packages.xml)
rm -f ${MODDIR}/packages.xml

if [ -z "${PACKAGE_INFO}" ]; then
	err "app not installed"
	exit
fi

BASEPATH=$(echo ${PACKAGE_INFO} | awk -F 'codePath="' '{print $2}' | awk -F '"' '{print $1}')
VERSION=$(echo ${PACKAGE_INFO} | awk -F 'version="' '{print $2}' | awk -F '"' '{print $1}')

if [ ! -d "$BASEPATH/lib" ]; then
	err "zygote crashed (fix your ROM)"
	exit
fi

if [ "$VERSION" != "$PKG_VER" ] && [ "$VERSION" ]; then
	err "version mismatch (installed:${VERSION}, module:$PKG_VER)"
	exit
fi

grep "$PKG_NAME" /proc/mounts | while read -r line; do
	mp=${line#* } mp=${mp%% *}
	umount -l "${mp%%\\*}"
done

if ! chcon u:object_r:apk_data_file:s0 "$RVPATH"; then
	err "apk not found"
	exit
fi

mount -o bind "$RVPATH" "$BASEPATH/base.apk"
am force-stop "$PKG_NAME"

[ -f "$MODDIR/err" ] && mv -f "$MODDIR/err" "$MODDIR/module.prop"
```
**BE ATTENTION**, if you want to use second solution to fix this issue, you should also modify the PKG_VER variable in config file(e.g. ```PKG_VER=1545731520```), because packages.xml stores application versionCode, not versionName.

**Comment by daifiyum** [comment]
Test results indicate that ```dumpsys``` is not affected by SELinux, while ```pm path``` is impacted. To avoid modifying the PKG_VER value in the config file, the ```dumpsys``` related code can be retained, and other operations should use the ```packages.xml``` approach.
```
#!/system/bin/sh
MODDIR=${0%/*}
RVPATH=/data/adb/rvhc/${MODDIR##*/}.apk
. "$MODDIR/config"

err() {
  [ ! -f "$MODDIR/err" ] && cp "$MODDIR/module.prop" "$MODDIR/err"
  sed -i "s/^des.*/description=⚠️ Needs reflash: '${1}'/g" "$MODDIR/module.prop"
}

until [ "$(getprop sys.boot_completed)" = 1 ]; do sleep 1; done
until [ -d "/sdcard/Android" ]; do sleep 1; done

rm -f ${MODDIR}/packages.xml
if [ ! -f "/data/system/packages.xml" ]; then
  err "packages.xml not found"
  exit
elif [ -z "$(file /data/system/packages.xml | grep 'Binary')" ]; then
  cp -f /data/system/packages.xml ${MODDIR}/packages.xml
elif ! which abx2xml > /dev/null; then
  err "abx2xml tool not found"
  exit
else
  abx2xml /data/system/packages.xml ${MODDIR}/packages.xml
fi

PACKAGE_INFO=$(grep "<package name=\"${PKG_NAME}\"" ${MODDIR}/packages.xml)
rm -f ${MODDIR}/packages.xml

if [ -z "${PACKAGE_INFO}" ]; then
  err "app not installed"
  exit
fi

BASEPATH=$(echo ${PACKAGE_INFO} | awk -F 'codePath="' '{print $2}' | awk -F '"' '{print $1}')
# VERSION=$(echo ${PACKAGE_INFO} | awk -F 'version="' '{print $2}' | awk -F '"' '{print $1}')

if [ ! -d "$BASEPATH/lib" ]; then
  err "zygote crashed (fix your ROM)"
  exit
fi

# if [ "$VERSION" != "$PKG_VER" ] && [ "$VERSION" ]; then
#   err "version mismatch (installed:${VERSION}, module:$PKG_VER)"
#   exit
# fi
VERSION=$(dumpsys package "$PKG_NAME" | grep -m1 versionName) VERSION="${VERSION#*=}"
if [ "$VERSION" != "$PKG_VER" ] && [ "$VERSION" ]; then
	err "version mismatch (installed:${VERSION}, module:$PKG_VER)"
	exit
fi

grep "$PKG_NAME" /proc/mounts | while read -r line; do
  mp=${line#* } mp=${mp%% *}
  umount -l "${mp%%\\*}"
done

if ! chcon u:object_r:apk_data_file:s0 "$RVPATH"; then
  err "apk not found"
  exit
fi

mount -o bind "$RVPATH" "$BASEPATH/base.apk"
am force-stop "$PKG_NAME"

[ -f "$MODDIR/err" ] && mv -f "$MODDIR/err" "$MODDIR/module.prop"
```

**Comment by daifiyum** [comment]
I made some modifications, and it runs normally now.
https://github.com/j-hc/revanced-magisk-module/pull/492

**Comment by daifiyum** [comment]
The usable module compiled independently using the second solution provided by https://github.com/bmax121/APatch/issues/571#issuecomment-2267368106

**Comment by xChickens** [comment]
Latest version of https://github.com/j-hc/revanced-magisk-module has `NVBASE` removed from service.sh. However, it doesn't have the SELinux `setenforce` commands, so this issue still exists in master. 

Note that the example given in this post does not have the `setenforce` commands. I added it to my fork of the package and itfixes this issue, except for one of my apps losing its ad removal mod after rebooting (Reddit Sync).

I'm gonna create a cross issue to that package.

**Comment by daifiyum** [comment]
> 最新版本的https://github.com/j-hc/revanced-magisk-module已从`NVBASE`service.sh 中移除。但是，它没有 SELinux`setenforce`命令，因此该问题在 master 中仍然存在。
> 
> 请注意，本文中给出的示例没有命令`setenforce`。我将其添加到我的软件包分支中，它修复了这个问题，但我的一个应用程序在重启后丢失了广告删除模式（Reddit Sync）。
> 
> 我将针对该包创建一个交叉问题。

根据此问题：https://github.com/termux/termux-packages/discussions/8292#discussioncomment-5102555
service.sh中第九行，修改为如下代码即可修复：
```
BASEPATH=$(pm path "$PKG_NAME" 2>&1 </dev/null)
```

**Comment by daifiyum** [comment]
> Latest version of https://github.com/j-hc/revanced-magisk-module has `NVBASE` removed from service.sh. However, it doesn't have the SELinux `setenforce` commands, so this issue still exists in master.
> 
> Note that the example given in this post does not have the `setenforce` commands. I added it to my fork of the package and itfixes this issue, except for one of my apps losing its ad removal mod after rebooting (Reddit Sync).
> 
> I'm gonna create a cross issue to that package.

你这个解决方案并不优雅，估计Revanced那边不会同意

**Comment by daifiyum** [comment]
According to this question: https://github.com/termux/termux-packages/discussions/8292
Modify the ninth line in service.sh to the following code to fix it:

BASEPATH=$(pm path "$PKG_NAME" 2>&1 </dev/null)

**Comment by daifiyum** [comment]
> Latest version of https://github.com/j-hc/revanced-magisk-module has `NVBASE` removed from service.sh. However, it doesn't have the SELinux `setenforce` commands, so this issue still exists in master.
> 
> Note that the example given in this post does not have the `setenforce` commands. I added it to my fork of the package and itfixes this issue, except for one of my apps losing its ad removal mod after rebooting (Reddit Sync).
> 
> I'm gonna create a cross issue to that package.

According to this question: https://github.com/termux/termux-packages/discussions/8292
Modify the ninth line in service.sh to the following code to fix it:

BASEPATH=$(pm path "$PKG_NAME" 2>&1 </dev/null)
