### ISSUE TITLE
【Question】How does apatch handle OTA upgrade?

### ISSUE THREAD

**Issue by fatinghenji** [bmax121/APatch#58]
As the title asks, how does apatch handle OTAs? Can I keep apatch when I do an OTA upgrade? Or do I need to process and install apatch after each OTA upgrade?

**Comment by marat2509** [comment]
> need to process and install apatch after each OTA upgrade?

**Comment by symbuzzer** [comment]
Is this planning to add?

**Comment by marat2509** [comment]
> Is this planning to add?

More likely no than yes

**Comment by ponces** [comment]
A possibility would be to flash on the inactive slot as Magisk does on a/b devices...

**Comment by ponces** [comment]
No possibility for non a/b devices besides uninstalling/installing again

**Comment by symbuzzer** [comment]
Is not possible with an addon.d script too?

**Comment by symbuzzer** [comment]
https://github.com/symbuzzer/kernel-ota-survival-addon.d-script

**Comment by symbuzzer** [comment]
> https://github.com/symbuzzer/kernel-ota-survival-addon.d-script @marat2509

I added both old boot-only devices and new boot_a, boot_b devices support and succesfully tested on Mi 10T Pro (boot only) and Poco X3 GT (boot_ab) devices.

**Comment by bmax121** [comment]
#265

**Comment by MaxMorfiX** [comment]
I tried to make a tool which does that automatically for you (not just prevens the kernel for updating, but actually re-patches it with each ota), you could try it out here if you want to: https://github.com/MaxMorfiX/APatch-OTA-survival-script
