### ISSUE TITLE
Install to inactive slot after OTA

### ISSUE THREAD

**Issue by fc-dj** [bmax121/APatch#630]
### Please check before submitting an issue/在提交 issue 前请检查

- [X] I have searched the issues and haven't found anything relevant/我已经搜索了 issues 列表，没有发现于本问题相关内容
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch/修复失败或刷入修补后镜像不能启动，请前往 KernelPatch 提问
- [ ] I will upload bugreport file in APatch Manager - Settings - Report log/我会上传 bureport 文件从 APatch 管理器 - 设置 - 发送日志
- [x] I know how to reproduce the issue which may not be specific to my device/我知道如何重新复现这个问题

### Version requirement/版本要求

- [X] I am using latest CI version of APatch/我正在使用最新 CI 版本

### Describe the bug/描述 bug

After patching image in the inactive slot, APatch erroneously sets boot slot as the current one instead of the inactive one.
After rebooting, OTA fails because it didn't boot to the second slot. Tried both rebooting from APatch and from system update app.
Workaround: after patching inactive slot, manually select second slot via terminal worked to complete the update and boot retaining patched kernel. This confirms there is no issue other than slot selection.
Using HyperOs.

### Reproduce method/复现方法

Perform OTA, don't reboot, install to inactive slot from APatch, click reboot (both in APatch or updater).

### Expected behavior/预期行为

Switch to inactive boot slot

### Actual behaviour /实际行为

Boots from the active slot instead of the updated one.

### Device Name/设备名称

POCO M6 Pro (emerald)

### OS Version/系统版本

HyperOS 1.0.3.0 EEA

### APatch Version/APatch 版本

10763

### Kernel Version/内核版本

5.10.198

### KernelPatch Version/KernelPatch 版本

0.10.7

### Additional context/其他信息

.

**Comment by marat2509** [comment]
> [x] I am using latest CI version of APatch/我正在使用最新 CI 版本
