### ISSUE TITLE
APatch not working on my device with crDroid

### ISSUE THREAD

**Issue by ang3lo-azevedo** [bmax121/APatch#647]
### Please check before submitting an issue/在提交 issue 前请检查

- [X] I have searched the issues and haven't found anything relevant/我已经搜索了 issues 列表，没有发现于本问题相关内容
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch/修复失败或刷入修补后镜像不能启动，请前往 KernelPatch 提问
- [X] I will upload bugreport file in APatch Manager - Settings - Report log/我会上传 bureport 文件从 APatch 管理器 - 设置 - 发送日志
- [X] I know how to reproduce the issue which may not be specific to my device/我知道如何重新复现这个问题

### Version requirement/版本要求

- [X] I am using latest CI version of APatch/我正在使用最新 CI 版本

### Describe the bug/描述 bug

I can't install APatch on my Nothing Phone 1 running crDroid 10.7.
I can patch the boot image but when I apply it the app says that APatch is not applied.

### Reproduce method/复现方法

Tried to install

### Expected behavior/预期行为

When flashed the patched boot image APatch should be running.

### Actual behaviour /实际行为

The app says that APatch isn't installed.

### Device Name/设备名称

Nothing Phone 1 (Spacewar)

### OS Version/系统版本

crDroid 10.7

### APatch Version/APatch 版本

10763

### Kernel Version/内核版本

5.4.259-perf+

### KernelPatch Version/KernelPatch 版本

0.10.7

### Additional context/其他信息

[APatch_bugreport_2024-09-02_12_42.tar.gz](https://github.com/user-attachments/files/16837016/APatch_bugreport_2024-09-02_12_42.tar.gz)

**Comment by gyrorayo** [comment]
have you tried patching **init_boot.img**?

**Comment by marat2509** [comment]
> * I am using latest CI version of APatch/我正在使用最新 CI 版本


> ### KernelPatch Version/KernelPatch 版本
> 0.10.7

Try latest nightly version...

**Comment by marat2509** [comment]
> cant give root permissions to any app

This is rather a general bug of the application when it cannot parse the list of installed applications

**Comment by OG-Feromax** [comment]
> > cant give root permissions to any app
> 
> This is rather a general bug of the application when it cannot parse the list of installed applications

Same issue here.
so, does it work? Is there a way to install modules and give root permissions to apps?
