### ISSUE TITLE
Inbuilt Busybox getopt is not found

### ISSUE THREAD

**Issue by hopez13** [bmax121/APatch#700]
### Please check before submitting an issue/在提交 issue 前请检查

- [X] I have searched the issues and haven't found anything relevant/我已经搜索了 issues 列表，没有发现于本问题相关内容
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch/修复失败或刷入修补后镜像不能启动，请前往 KernelPatch 提问
- [X] I will upload bugreport file in APatch Manager - Settings - Report log/我会上传 bureport 文件从 APatch 管理器 - 设置 - 发送日志
- [X] I know how to reproduce the issue which may not be specific to my device/我知道如何重新复现这个问题

### Version requirement/版本要求

- [X] I am using latest CI version of APatch/我正在使用最新 CI 版本

### Describe the bug/描述 bug

getopt is not found if invoked directly 
it works only if invoked like `busybox getopt` 

@osm0sis 

### Reproduce method/复现方法

su
getopt

### Expected behavior/预期行为

getopt should work with being prefixed with `busybox`

### Actual behaviour /实际行为

getopt directly invoked doesn't work

### Screenshots/截图

![IMG_20241005_131056](https://github.com/user-attachments/assets/809b17f6-37d7-4f2c-8c2e-235d21161270)

### Device Name/设备名称

Mi

### OS Version/系统版本

Hyper OS 1.0.7

### APatch Version/APatch 版本

10933

### Kernel Version/内核版本

5.10

### KernelPatch Version/KernelPatch 版本

0.11.1

### Additional context/其他信息

 Busybox Is Broken  
specifically getopt command  can't be invoked directly might be sys link issue 

they maybe more commands broken but I haven't tested all

**Comment by osm0sis** [comment]
Invalid, root solution included busybox binaries don't have their applets on the $PATH.
