### ISSUE TITLE
root detected by Chinatax 电子税务局

### ISSUE THREAD

**Issue by MaverickYing** [bmax121/APatch#706]
### Please check before submitting an issue/在提交 issue 前请检查

- [X] I have searched the issues and haven't found anything relevant/我已经搜索了 issues 列表，没有发现于本问题相关内容
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch/修复失败或刷入修补后镜像不能启动，请前往 KernelPatch 提问
- [X] I will upload bugreport file in APatch Manager - Settings - Report log/我会上传 bureport 文件从 APatch 管理器 - 设置 - 发送日志
- [X] I know how to reproduce the issue which may not be specific to my device/我知道如何重新复现这个问题

### Version requirement/版本要求

- [X] I am using latest CI version of APatch/我正在使用最新 CI 版本

### Describe the bug/描述 bug

root detected
app: 电子税务局 cn.gov.chinatax.gt4.app
version: 1.1.1(330)
![Screenshot_2024-10-08-15-07-49-93_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/user-attachments/assets/357691d9-f822-4964-b033-eba806705a85)

### Reproduce method/复现方法

1 install 电子税务局
2 click app
3 ctd

### Expected behavior/预期行为

used normally

### Actual behaviour /实际行为

crash with notification

### Screenshots/截图

![Screenshot_2024-10-08-14-58-31-48_b783bf344239542886fee7b48fa4b892](https://github.com/user-attachments/assets/d00eb6bf-941b-4b32-bb22-292eaa9a555b)

### Logs/日志

[APatch_bugreport_2024-10-08_14_56.tar.gz](https://github.com/user-attachments/files/17289262/APatch_bugreport_2024-10-08_14_56.tar.gz)

### Device Name/设备名称

Oneplus 12

### OS Version/系统版本

Coloros 12 PJD110_14.0.0.850(CN01U130P00)

### APatch Version/APatch 版本

10763

### Kernel Version/内核版本

6.1.57

### KernelPatch Version/KernelPatch 版本

0.10.7

### Additional context/其他信息

![Screenshot_2024-10-08-15-06-19-40](https://github.com/user-attachments/assets/2ab59f62-3010-4513-aa9d-c414fd2c3491)

**Comment by Ai686Leo** [comment]
加排除列表并在模块zygisk设置遵守排除列表，然后把应用数据清空一下试试？

**Comment by MaverickYing** [comment]
找到问题了 是lsposed的问题

**Comment by FrankieZJWZ** [comment]
是不是用原版的LSP 就可以？
