### ISSUE TITLE
[question]how can i get the install environment in module install scripts?

### ISSUE THREAD

**Issue by SivonZn** [bmax121/APatch#71]
just as KSU's "$KSU" or magisk's "$(which magisk)"
and version check as $MAGISK_VER($MAGISK_VER_CODE) or $KSU_VER_CODE(ksud)

**Comment by marat2509** [comment]
There is no clear variable for detecting the environment yet. I think we'll add something like APD_VER in the near future

**Comment by Zenlua** [comment]
Just check 
apd && echo "It's apatch"
ksud && echo "It's ksu"
magisk && echo "It's magisk"
Maybe try this command

**Comment by SivonZn** [comment]
> Just check 
> apd && echo "It's apatch"
> ksud && echo "It's ksu"
> magisk && echo "It's magisk"
> Maybe try this command

thanks，it works well
