### ISSUE TITLE
Apatch flashed and booted successfully. But it said Authentication failed when entering super key.

### ISSUE THREAD

**Issue by NotchApple1703** [bmax121/APatch#735]
### Please check before submitting an issue/在提交 issue 前请检查

- [X] I have searched the issues and haven't found anything relevant/我已经搜索了 issues 列表，没有发现于本问题相关内容
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch/修复失败或刷入修补后镜像不能启动，请前往 KernelPatch 提问
- [X] I will upload bugreport file in APatch Manager - Settings - Report log/我会上传 bureport 文件从 APatch 管理器 - 设置 - 发送日志
- [x] I know how to reproduce the issue which may not be specific to my device/我知道如何重新复现这个问题

### Version requirement/版本要求

- [X] I am using latest CI version of APatch/我正在使用最新 CI 版本

### Describe the bug/描述 bug

I've flashed boot.img and booted successfully. But it said Authentication failed when entering super key.

### Reproduce method/复现方法

Install Apatch

### Expected behavior/预期行为

Install Apatch successfully

### Actual behaviour /实际行为

Failed

### Logs/日志

[APatch_bugreport_2024-10-23_16_53.tar.gz](https://github.com/user-attachments/files/17488802/APatch_bugreport_2024-10-23_16_53.tar.gz)

### Device Name/设备名称

Xiaomi Redmi K40 (alioth)

### OS Version/系统版本

CrDroid 10.9

### APatch Version/APatch 版本

10763

### Kernel Version/内核版本

4.19.320 

### KernelPatch Version/KernelPatch 版本

10763

### Additional context/其他信息

This is my CrDroid boot.img that I've extracted from payload.bin [boot.zip](https://github.com/user-attachments/files/17488845/boot.zip)

I've also tried latest CI build but it stucks at boot logo after flashing.
I've successfully installed Apatch on many other roms so I believe this is caused by CrDroid.

**Comment by marat2509** [comment]
> [x] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch/修复失败或刷入修补后镜像不能启动，请前往 KernelPatch 提问
