### ISSUE TITLE
stuck at "detecting current package"

### ISSUE THREAD

**Issue by paaavann** [bmax121/APatch#737]
### Please check before submitting an issue/在提交 issue 前请检查

- [X] I have searched the issues and haven't found anything relevant/我已经搜索了 issues 列表，没有发现于本问题相关内容
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch/修复失败或刷入修补后镜像不能启动，请前往 KernelPatch 提问
- [X] I will upload bugreport file in APatch Manager - Settings - Report log/我会上传 bureport 文件从 APatch 管理器 - 设置 - 发送日志
- [X] I know how to reproduce the issue which may not be specific to my device/我知道如何重新复现这个问题

### Version requirement/版本要求

- [X] I am using latest CI version of APatch/我正在使用最新 CI 版本

### Describe the bug/描述 bug

STUCK AT DETECTING CURRENT PACKAGE

### Reproduce method/复现方法

rename apk to zip then install

### Expected behavior/预期行为

Should patch boot.img

### Actual behaviour /实际行为

STUCK AT DETECTING CURRENT PACKAGE

### Device Name/设备名称

POCO X6

### OS Version/系统版本

Tried in many OS still same.

### APatch Version/APatch 版本

APatch_10763_10763-release-signed.apk

### Kernel Version/内核版本

5.10

### KernelPatch Version/KernelPatch 版本

dont know

### Additional context/其他信息

STUCK AT DETECTING CURRENT PACKAGE

**Comment by marat2509** [comment]
> [x] I am using latest CI version of APatch/我正在使用最新 CI 版本
