### ISSUE TITLE
Apatch flashed and booted successfully. But it said Authentication failed when entering super key.

### ISSUE THREAD

**Issue by theAkito** [bmax121/APatch#742]
### Please check before submitting an issue/在提交 issue 前请检查

- [X] I have searched the issues and haven't found anything relevant/我已经搜索了 issues 列表，没有发现于本问题相关内容
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch/修复失败或刷入修补后镜像不能启动，请前往 KernelPatch 提问
- [X] I will upload bugreport file in APatch Manager - Settings - Report log/我会上传 bureport 文件从 APatch 管理器 - 设置 - 发送日志
- [X] I know how to reproduce the issue which may not be specific to my device/我知道如何重新复现这个问题

### Version requirement/版本要求

- [X] I am using latest CI version of APatch/我正在使用最新 CI 版本

### Describe the bug/描述 bug

Patch worked, boot worked, but Super Key fails authentication.

### Reproduce method/复现方法

1. Patch
2. Flash
3. Boot
4. Super Key -> Authentication Failed

### Expected behavior/预期行为

Super Key Authenticated

### Actual behaviour /实际行为

Super Key Authentication Failed

### Device Name/设备名称

Xiaomi POCO X4 Pro 5G (veux)

### OS Version/系统版本

lineage-21.0-20240912-UNOFFICIAL-veux (Android 14)

### APatch Version/APatch 版本

10763 | 10657

### Kernel Version/内核版本

5.4.268~positron/2472b397

### KernelPatch Version/KernelPatch 版本

¯\_(ツ)_/¯

### Additional context/其他信息

* https://github.com/bmax121/APatch/issues/735
* https://xdaforums.com/t/dev-apatch-an-alternative-root-solution-to-kernelsu-and-magisk.4655727/post-89775266

Tried everything. Still, did not work.

**Comment by marat2509** [comment]
> [x] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch/修复失败或刷入修补后镜像不能启动，请前往 KernelPatch 提问
