### ISSUE TITLE
Apatch crashing, resetting after granting su wont recognize root

### ISSUE THREAD

**Issue by jooomoooj** [bmax121/APatch#751]
### Please check before submitting an issue/在提交 issue 前请检查

- [X] I have searched the issues and haven't found anything relevant/我已经搜索了 issues 列表，没有发现于本问题相关内容
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch/修复失败或刷入修补后镜像不能启动，请前往 KernelPatch 提问
- [X] I will upload bugreport file in APatch Manager - Settings - Report log/我会上传 bureport 文件从 APatch 管理器 - 设置 - 发送日志
- [X] I know how to reproduce the issue which may not be specific to my device/我知道如何重新复现这个问题

### Version requirement/版本要求

- [X] I am using latest CI version of APatch/我正在使用最新 CI 版本

### Describe the bug/描述 bug

Apatch resetting itself 

https://github.com/user-attachments/assets/be02309e-18a9-47b2-a5db-a15dfaf04e5a

### Reproduce method/复现方法

Screenvideo included.

### Expected behavior/预期行为

Should retain its normal state

### Actual behaviour /实际行为

Crashing and su not granting

### Device Name/设备名称

Xiaomi Mi A1

### OS Version/系统版本

14

### APatch Version/APatch 版本

10995

### Kernel Version/内核版本

4.9.337

### KernelPatch Version/KernelPatch 版本

0.11.1

### Additional context/其他信息

Cant take logs, it wasnt recognizing su, screenvideo shows error code could help.

**Comment by Admirepowered** [comment]
Fixed
https://github.com/bmax121/APatch/actions/runs/11553287817
