### ISSUE TITLE
关于modules目录下文件可读的问题

### ISSUE THREAD

**Issue by CC0126** [bmax121/APatch#77]
您好，我是刚刚使用apatch的开发者，但是我发现相比ksu和magisk，apatch的/data/adb/modules目录下的文件在引导完成后是不可见的，但许多老的模块需要读取或修改这里面的文件，想问一下是否有兼容模式可以让该路径下的文件在引导完成后保留？

**Comment by wenhelinlu** [comment]
APatch把模块合并打包成img格式了，但是如果安装了AList或者Box4Magisk模块，需要修改配置文件的，就没法操作了。

**Comment by liushihowe** [comment]
![Screenshot_2024-01-27-17-14-41-009_xyz.chz.bfm.jpg](https://github.com/bmax121/APatch/assets/127091329/dbf9efe8-2b79-4baa-a3fb-36426dee9058)

无法发现模块，如果授予root权限就直接闪退
