### ISSUE TITLE
some APEX apps can't be removed

### ISSUE THREAD

**Issue by XingLiAl** [bmax121/APatch#771]
### Please check before submitting an issue/在提交 issue 前请检查

- [X] I have searched the issues and haven't found anything relevant/我已经搜索了 issues 列表，没有发现于本问题相关内容
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch/修复失败或刷入修补后镜像不能启动，请前往 KernelPatch 提问
- [X] I will upload bugreport file in APatch Manager - Settings - Report log/我会上传 bureport 文件从 APatch 管理器 - 设置 - 发送日志
- [X] I know how to reproduce the issue which may not be specific to my device/我知道如何重新复现这个问题

### Version requirement/版本要求

- [X] I am using latest CI version of APatch/我正在使用最新 CI 版本

### Describe the bug/描述 bug

After remove .capex files in system{,_ext}/apex using REMOVE=PATH field in customize.sh, the .capex files disappear, but there're still corresponding directory in /apex and corresponding package still in the package list.
And after remove .apex files in system{,_ext} using REMOVE=PATH field in customize.sh, the .apex files disappear, and the corresponding package disappears from the package list, but there're still corresponding directory in /apex, which is strange.

### Reproduce method/复现方法

1. Create a module installer zip
2. Create customize.sh and write REMOVE="/system/apex/xxx.apex\n/system/apex/xxx.capex"

### Expected behavior/预期行为

The apex/capex files in system{,_ext}/apex disappear, the corresponding directories in /apex disappear, and the corresponding packages disappear from package list

### Actual behaviour /实际行为

After remove .capex files in system{,_ext}/apex using REMOVE=PATH field in customize.sh, the .capex files disappear, but there're still corresponding directory in /apex and corresponding package still in the package list.
And after remove .apex files in system{,_ext} using REMOVE=PATH field in customize.sh, the .apex files disappear, and the corresponding package disappears from the package list, but there're still corresponding directory in /apex. 

### Device Name/设备名称

Redmi Note 11T Pro

### OS Version/系统版本

HyperOS 1.0.5

### APatch Version/APatch 版本

Apatch Next 0.11.2 (11021)

### Kernel Version/内核版本

5.10.198-android12-9-00085-g226a9632f13d-ab11136126

### KernelPatch Version/KernelPatch 版本

0.11.2

### Additional context/其他信息

Module that removes some apex/.capex files.
[lialh4-trash-away.zip](https://github.com/user-attachments/files/17682490/lialh4-trash-away.zip)

**Comment by marat2509** [comment]
> Apatch Next 0.11.2 (11021)

We do not provide support for APatch forks/modifications
