### ISSUE TITLE
vivoy3 boot.img patch fail

### ISSUE THREAD

**Issue by wzfxue** [bmax121/APatch#779]
### Please check before submitting an issue/在提交 issue 前请检查

- [X] I have searched the issues and haven't found anything relevant/我已经搜索了 issues 列表，没有发现于本问题相关内容
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch/修复失败或刷入修补后镜像不能启动，请前往 KernelPatch 提问
- [X] I will upload bugreport file in APatch Manager - Settings - Report log/我会上传 bureport 文件从 APatch 管理器 - 设置 - 发送日志
- [ ] I know how to reproduce the issue which may not be specific to my device/我知道如何重新复现这个问题

### Version requirement/版本要求

- [X] I am using latest CI version of APatch/我正在使用最新 CI 版本

### Describe the bug/描述 bug

修补失败

### Reproduce method/复现方法

https://cowtransfer.com/s/9a23414ffa3948 点击链接查看 [ boot.img ] ，或访问奶牛快传 cowtransfer.com 输入传输口令 yppp25 查看；

### Expected behavior/预期行为

修补成功

### Actual behaviour /实际行为

修补失败

### Screenshots/截图

![1](https://github.com/user-attachments/assets/78b8cb73-d315-4f71-8179-f566aafc39ae)
![2](https://github.com/user-attachments/assets/41903237-5c27-4e8c-b2cc-04b28b0b8ece)

### Logs/日志

pic

### Device Name/设备名称

vivo

### OS Version/系统版本

android9

### APatch Version/APatch 版本

10763

### Kernel Version/内核版本

4.9.117+

### KernelPatch Version/KernelPatch 版本

0.10.7

### Additional context/其他信息

https://cowtransfer.com/s/9a23414ffa3948 点击链接查看 [ boot.img ] ，或访问奶牛快传 cowtransfer.com 输入传输口令 yppp25 查看；

**Comment by marat2509** [comment]
> * If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch/修复失败或刷入修补后镜像不能启动，请前往 KernelPatch 提问



> * I am using latest CI version of APatch/我正在使用最新 CI 版本
