### ISSUE TITLE
兼容Shamiko模块

### ISSUE THREAD

**Issue by Nya-Cow** [bmax121/APatch#788]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

无法安装模块

### Describe the solution you'd like/描述你想要的解决方案

像kernelsu一样支持Shamiko

### Describe alternatives you've considered/描述您考虑过的备选方案

开发Apatch专用的"shamiko"

### Additional context/其他信息

无

**Comment by VisionR1** [comment]
Yeah, unfortunately the latest version of shamiko is not supported, only a old verision v.0.7.4 but is too old.
You must ask the shamiko devs and not here.

**Comment by 1q23lyc45** [comment]
https://github.com/snake-4/Zygisk-Assistant 这个模块不行吗？已经专门适配了Apatch而且开源。

https://apatch.dev/zh_CN/faq.html
Shamiko 是专有软件，无法适配。
APatch 开发者将不对任何因使用 Shamiko 导致的问题承担任何责任，你需要自行承担使用风险。

**Comment by Admirepowered** [comment]
模块作者的问题，与我们无关
