### ISSUE TITLE
禁止不了root权限，重启手机后app自动获得root权限

### ISSUE THREAD

**Issue by 456vv** [bmax121/APatch#805]
### Please check before submitting an issue/在提交 issue 前请检查

- [X] I have searched the issues and haven't found anything relevant/我已经搜索了 issues 列表，没有发现于本问题相关内容
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch/修复失败或刷入修补后镜像不能启动，请前往 KernelPatch 提问
- [X] I will upload bugreport file in APatch Manager - Settings - Report log/我会上传 bureport 文件从 APatch 管理器 - 设置 - 发送日志
- [ ] I know how to reproduce the issue which may not be specific to my device/我知道如何重新复现这个问题

### Version requirement/版本要求

- [X] I am using latest CI version of APatch/我正在使用最新 CI 版本

### Describe the bug/描述 bug

禁止不了root权限，重启手机后app自动获得root权限；其它都可以禁止，就这个不能，奇怪了？
app：com.unicom.woshipin
名称：沃视频
ver：8.1.0

### Reproduce method/复现方法

重启手机后app自动获得root权限

### Expected behavior/预期行为

不给权限的，不能有root权限。

### Actual behaviour /实际行为

已禁止所有app权限和模块，重启手机后 com.unicom.woshipin 已经自己获得root权限了

### Device Name/设备名称

一加

### OS Version/系统版本

11

### APatch Version/APatch 版本

10763

### Kernel Version/内核版本

4.9.227

### KernelPatch Version/KernelPatch 版本

0.10.7

### Additional context/其他信息

[Uploading APatch_bugreport_2024-11-26_10_57.tar.gz…]()

**Comment by xhxjsk** [comment]
不是最新ci版本，为什么不看更新日志？https://github.com/bmax121/APatch/releases/tag/10763
不是写了吗？

**Comment by xhxjsk** [comment]
> ### 请在提交问题/在提交问题前进行检查
> * [x] 我已经搜索了这些问题，还没有找到任何相关的/我已经搜索了问题
> * [x] 如果补丁失败，root失败，或者设备在闪烁新的boot. img后无法引导。请转到KernelPatch/修复失败或刷入修补后镜像不能启动
> * [x] 我将上传bugreport文件在APatch Manager-Settings-Report日志/我会上传 bureport
> * [ ] 我知道如何复制可能不特定于我的设备/我知道如何重新复现这个问题的问题
> 
> ### 版本要求/版本要求
> * [x] 我使用的是APatch/我正在使用最新 CI
> 
> ### 描述bug/描述 bug
> 禁止不了root权限，重启手机后app自动获得root权限；其它都可以禁止，就这个不能，奇怪了？app：com.unicom.woshipin 名称：沃视频ver：8.1.0
> 
> ### 复制法/复现方法
> 重启手机后app自动获得root权限
> 
> ### 预期行为/预期行为
> 不给权限的，不能有root权限。
> 
> ### 实际行为/实际行为
> 已禁止所有app权限和模块，重启手机后 com.unicom.woshipin 已经自己获得root权限了
> 
> ### 截图/截图
> _无回应_
> 
> ### 日志/日志
> _无回应_
> 
> ### 设备名/设备名称
> 一加
> 
> ### OS版本/系统版本
> 11
> 
> ### APatch版本/APatch版本
> 10763
> 
> ### 内核版/内核版本
> 4.9.227
> 
> ### KernelPatch版本/KernelPatch版本
> 0.10.7
> 
> ### 附加上下文/其他信息
> 上传APatch_bugreport_2024-11-26_10_57.tar.gz……



> ### Please check before submitting an issue/在提交 issue 前请检查
> * [x]  I have searched the issues and haven't found anything relevant/我已经搜索了 issues 列表，没有发现于本问题相关内容
> * [x]  If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch/修复失败或刷入修补后镜像不能启动，请前往 KernelPatch 提问
> * [x]  I will upload bugreport file in APatch Manager - Settings - Report log/我会上传 bureport 文件从 APatch 管理器 - 设置 - 发送日志
> * [ ]  I know how to reproduce the issue which may not be specific to my device/我知道如何重新复现这个问题
> 
> ### Version requirement/版本要求
> * [x]  I am using latest CI version of APatch/我正在使用最新 CI 版本
> 
> ### Describe the bug/描述 bug
> 禁止不了root权限，重启手机后app自动获得root权限；其它都可以禁止，就这个不能，奇怪了？ app：com.unicom.woshipin 名称：沃视频 ver：8.1.0
> 
> ### Reproduce method/复现方法
> 重启手机后app自动获得root权限
> 
> ### Expected behavior/预期行为
> 不给权限的，不能有root权限。
> 
> ### Actual behaviour /实际行为
> 已禁止所有app权限和模块，重启手机后 com.unicom.woshipin 已经自己获得root权限了
> 
> ### Screenshots/截图
> _No response_
> 
> ### Logs/日志
> _No response_
> 
> ### Device Name/设备名称
> 一加
> 
> ### OS Version/系统版本
> 11
> 
> ### APatch Version/APatch 版本
> 10763
> 
> ### Kernel Version/内核版本
> 4.9.227
> 
> ### KernelPatch Version/KernelPatch 版本
> 0.10.7
> 
> ### Additional context/其他信息
> Uploading APatch_bugreport_2024-11-26_10_57.tar.gz…

不是最新ci版本，为什么不看更新日志？https://github.com/bmax121/APatch/releases/tag/10763
不是写了吗？
