### ISSUE TITLE
银行类软件在未经授权的情况下获取了root权限

### ISSUE THREAD

**Issue by sxrking** [bmax121/APatch#822]
### Please check before submitting an issue/在提交 issue 前请检查

- [X] I have searched the issues and haven't found anything relevant/我已经搜索了 issues 列表，没有发现于本问题相关内容
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch/修复失败或刷入修补后镜像不能启动，请前往 KernelPatch 提问
- [X] I will upload bugreport file in APatch Manager - Settings - Report log/我会上传 bureport 文件从 APatch 管理器 - 设置 - 发送日志
- [X] I know how to reproduce the issue which may not be specific to my device/我知道如何重新复现这个问题

### Version requirement/版本要求

- [X] I am using latest CI version of APatch/我正在使用最新 CI 版本

### Describe the bug/描述 bug

如题，我安装好了银行软件后被检测root，打开管理器后发现未经授权却授予了root权限

### Reproduce method/复现方法

安装后直接获得root权限；关闭授权后重启系统再次获得权限

### Expected behavior/预期行为

希望不要自动授予root权限

### Actual behaviour /实际行为

在安装好数字人民币，广西农信，中信银行后未经授权授予了root权限

### Screenshots/截图

![Screenshot_2024-12-03-23-14-05-76](https://github.com/user-attachments/assets/fe2b6bf6-06d9-497d-ae99-4452b1bd15d7)

### Logs/日志

[Uploading APatch_bugreport_2024-12-03_23_09.tar.gz…]()

### Device Name/设备名称

OnePlus9R LE2100

### OS Version/系统版本

LE2100_14.0.0.603(CN01)

### APatch Version/APatch 版本

10763

### Kernel Version/内核版本

4.19.157-perf+

### KernelPatch Version/KernelPatch 版本

0.10.7

### Additional context/其他信息

[Uploading APatch_bugreport_2024-12-03_23_09.tar.gz…]()

**Comment by marat2509** [comment]
1:

> [x] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch/修复失败或刷入修补后镜像不能启动，请前往 KernelPatch 提问


2:

> [x] I am using latest CI version of APatch/我正在使用最新 CI 版本

3. No logs
