### ISSUE TITLE
it´s not flashing on s23 ultra. i get in bootloop

### ISSUE THREAD

**Issue by windy123456788** [bmax121/APatch#828]
### Please check before submitting an issue/在提交 issue 前请检查

- [X] I have searched the issues and haven't found anything relevant/我已经搜索了 issues 列表，没有发现于本问题相关内容
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch/修复失败或刷入修补后镜像不能启动，请前往 KernelPatch 提问
- [X] I will upload bugreport file in APatch Manager - Settings - Report log/我会上传 bureport 文件从 APatch 管理器 - 设置 - 发送日志
- [X] I know how to reproduce the issue which may not be specific to my device/我知道如何重新复现这个问题

### Version requirement/版本要求

- [X] I am using latest CI version of APatch/我正在使用最新 CI 版本

### Describe the bug/描述 bug

i have a s23 ultra kernel android13-5.15.123.android13 after i patched the boot img, i get stuck in bootloop. i found a way to revert it, but i have to install kernel su patch and then pactch it again with the apatch. the problem is that i have two root managers now, and nothing of safetynew will work. i need help. fix this bug in apatch please.

### Reproduce method/复现方法

i get this error every single way, via twrp or odin

### Expected behavior/预期行为

to flash, and work

### Actual behaviour /实际行为

dont work, i get in bootloop

### Device Name/设备名称

s23ultra

### OS Version/系统版本

android 14 one ui 6.1

### APatch Version/APatch 版本

latest

### Kernel Version/内核版本

android 13- 5.15.123

### KernelPatch Version/KernelPatch 版本

107somthing

### Additional context/其他信息

the thing is, the patcher is not working properly. i can't give you the log cause i dont want to flash it again

**Comment by marat2509** [comment]
> ### Please check before submitting an issue/在提交 issue 前请检查
> * [x]  I have searched the issues and haven't found anything relevant/我已经搜索了 issues 列表，没有发现于本问题相关内容
> * [x]  If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch/修复失败或刷入修补后镜像不能启动，请前往 KernelPatch 提问
> * [x]  I will upload bugreport file in APatch Manager - Settings - Report log/我会上传 bureport 文件从 APatch 管理器 - 设置 - 发送日志
> * [x]  I know how to reproduce the issue which may not be specific to my device/我知道如何重新复现这个问题
> 
> ### Version requirement/版本要求
> * [x]  I am using latest CI version of APatch/我正在使用最新 CI 版本

No. Make a issue using the template
