### ISSUE TITLE
OverlayFS, no space left on device

### ISSUE THREAD

**Issue by DADA30000** [bmax121/APatch#835]
### Please check before submitting an issue/在提交 issue 前请检查

- [X] I have searched the issues and haven't found anything relevant/我已经搜索了 issues 列表，没有发现于本问题相关内容
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch/修复失败或刷入修补后镜像不能启动，请前往 KernelPatch 提问
- [X] I will upload bugreport file in APatch Manager - Settings - Report log/我会上传 bureport 文件从 APatch 管理器 - 设置 - 发送日志
- [ ] I know how to reproduce the issue which may not be specific to my device/我知道如何重新复现这个问题

### Version requirement/版本要求

- [X] I am using latest CI version of APatch/我正在使用最新 CI 版本

### Describe the bug/描述 bug

I'm trying to systemize google app, I tried systemize module, I tried doing  .rw stuff in /data/adb/module
I'm getting this mysterious error "No space left on this device.", although I still have plenty of space
It gives me this error when file size is more than ~250 MB

### Reproduce method/复现方法

. 

### Expected behavior/预期行为

It should let me transfery files to overlayfs

### Actual behaviour /实际行为

I get this error

### Device Name/设备名称

Realms 8i

### OS Version/系统版本

Android 14, crDroid 10.5

### APatch Version/APatch 版本

10763

### Kernel Version/内核版本

4.19.220

### KernelPatch Version/KernelPatch 版本

0.10.7

### Additional context/其他信息

[APatch_bugreport_2024-12-10_00_54.tar.gz](https://github.com/user-attachments/files/18068534/APatch_bugreport_2024-12-10_00_54.tar.gz)

**Comment by Admirepowered** [comment]
use nightly version https://nightly.link/bmax121/APatch/workflows/build/main/APatch
