### ISSUE TITLE
Ability to change/hide package name

### ISSUE THREAD

**Issue by PRiano-bio** [bmax121/APatch#836]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

As per title, some app detect root by detecting the presence of Apatch APK. Would be better to have the possibility to hide the name of the package.

### Describe the solution you'd like/描述你想要的解决方案

Ability to change/hide the package name 

### Describe alternatives you've considered/描述您考虑过的备选方案

Uninstalling the app 

### Additional context/其他信息

..

**Comment by VisionR1** [comment]
This feature exists in past, but removed due to cause some issues.

**Comment by marat2509** [comment]
https://github.com/bmax121/APatch/issues/544
