### ISSUE TITLE
魅族18s 10.3刷入后卡meizu

### ISSUE THREAD

**Issue by Zsflee** [bmax121/APatch#84]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch
- [X] I will upload bugreport file in APatch Manager - Settings - Report log
- [ ] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

boot链接  https://www.123pan.com/s/xykDVv-YNLN.html
修补后  刷入卡meizu
![微信图片_20240110193216](https://github.com/bmax121/APatch/assets/154646304/ec249e16-70eb-4c92-91c5-6d58a3fb9303)

### Screenshots

![微信图片_20240110193125](https://github.com/bmax121/APatch/assets/154646304/6d5fbd09-7c19-4289-b6d6-d1cf81f4b5e7)
![微信图片_20240110193216](https://github.com/bmax121/APatch/assets/154646304/0c2be257-f451-4076-96e3-d4d2b0472bd0)
![微信图片_20240110193321](https://github.com/bmax121/APatch/assets/154646304/377fb8b4-fe39-4f23-9aa2-bc43eda1ac37)

### Device info

- Device:魅族18s
- OS Version:flyme10.3
- APatch Version:10363
- Kernel Version:5.4.148

**Comment by ravindu644** [comment]
Enter the superkey to activate root.

**Comment by Zsflee** [comment]
> Enter the superkey to activate root.

Flashing in the boot directly causes the device to boot up and cannot access the system.

**Comment by Zsflee** [comment]
> Enter the superkey to activate root.

The screenshot I took is a system that only entered after flashing back to the official boot

**Comment by ravindu644** [comment]
> > Enter the superkey to activate root.
> 
> Flashing in the boot directly causes the device to boot up and cannot access the system.

touch issue ?

**Comment by ravindu644** [comment]
> > Enter the superkey to activate root.
> 
> The screenshot I took is a system that only entered after flashing back to the official boot

oh

**Comment by Zsflee** [comment]
Repairs are successful.
![微信图片_20240110194844](https://github.com/bmax121/APatch/assets/154646304/4380a119-7c76-4c23-b090-f50947726446)
![微信图片_20240110194847](https://github.com/bmax121/APatch/assets/154646304/4ac21060-e591-4c03-8696-2cf11f21da8f)
![微信图片_20240110194851](https://github.com/bmax121/APatch/assets/154646304/b7c3c682-cd5f-4aba-9b95-0e1562da94b2)

**Comment by ravindu644** [comment]
Can you try to flash the patched vbmeta.img from magisk?

how : 

Make a tar file using your original boot.img and vbmeta, then patch those files from magisk. Then extract the magisk patched tar, grab the vbmeta.img and flash it.

**Comment by bmax121** [comment]
Try newest version with KP >= 0.8.4 and APatch >= 10420

**Comment by wanghlstar** [comment]
10428 did not work yet on meizu 18  with flyme10.3

@Zsflee  are you ok ?

**Comment by Zsflee** [comment]
> 10428 did not work yet on meizu 18 with flyme10.3
> 
> @Zsflee are you ok ?

Still stuck on the first screen

**Comment by Zsflee** [comment]
> Try newest version with KP >= 0.8.4 and APatch >= 10420

Still stuck on the first screen  10440

**Comment by bmax121** [comment]
Can't fix without device. Maybe a future update can solve it
