### ISSUE TITLE
We got bugs🐞

### ISSUE THREAD

**Issue by ravindu644** [bmax121/APatch#92]
https://github.com/bmax121/APatch/assets/126038496/24b41ac3-22af-4a55-b9f3-dc0535855ca3

when changing language, back button seems not working, also it make the app crashes. btw it works.
![Screenshot_20240111_060753_One UI Home](https://github.com/bmax121/APatch/assets/126038496/a69fe43d-2025-4eb7-a317-5d88b152be4f)

App icon is darker too. Expected color = dark blue.

**Comment by alex193a** [comment]
I'm unable to reproduce the issue, it may be a device-specific issue. Do you have any logs you can provide?

https://github.com/bmax121/APatch/assets/8174240/d2db9262-4280-4995-bc05-143f5c9de24f

The icon was updated in pull request https://github.com/bmax121/APatch/pull/89

**Comment by ravindu644** [comment]
> I'm unable to reproduce the issue, it may be a device-specific issue. Do you have any logs you can provide?
> 
>  Record_2024-01-11-10-03-38.mp4 
> The icon was updated in pull request #89, @Traaanaelle can you confirm that the chosen color is correct?

Okay, I'll provide logs. yes, should an issue with one ui.

**Comment by ravindu644** [comment]
> I'm unable to reproduce the issue, it may be a device-specific issue. Do you have any logs you can provide?
> 
>  Record_2024-01-11-10-03-38.mp4 
> The icon was updated in pull request #89, @Traaanaelle can you confirm that the chosen color is correct?

[APatch_bugreport_2024-01-11_15_02.tar.gz](https://github.com/bmax121/APatch/files/13901191/APatch_bugreport_2024-01-11_15_02.tar.gz)

**Comment by Traaanaelle** [comment]
> I'm unable to reproduce the issue, it may be a device-specific issue. Do you have any logs you can provide?
> Record_2024-01-11-10-03-38.mp4
> 
> The icon was updated in pull request #89, @Traaanaelle can you confirm that the chosen color is correct?

Yes, I chose to replace the blue background with green
