### ISSUE TITLE
内核不支持overlayfs，如何解决，5.10-gki

### ISSUE THREAD

**Issue by ItosEO** [bmax121/APatch#99]
**内核版本：5.10.149-gki**
**设备型号：iQOO 9**
**Android版本：Android 13**

问题：
您好，我有一个设备是**5.10.149-gki**内核
我刷入ksu的ak3后无法使用模块系统，ksu管理器提示 **内核不支持overlay**
使用APatch后也是一样提示 **内核不支持overlayfs**，有什么方法可以解决么，或者可以通过patch启用overlayfs吗

**没有**内核源码
最好继续使用原厂映像，只是在上面修改而不是采用通用映像

**Comment by bmax121** [comment]
或许你可以将 magisk 模块代码抄过来

**Comment by ItosEO** [comment]
没太理解您的意思，但是我已经知道这是selinux的问题，现在正在和ksu维护者尝试解决，之后或许可以参考

**Comment by bmax121** [comment]
挺好，期待解决
